### PR TITLE
AC Automated Test - LRAC-8341 | master

### PR DESCRIPTION
**Pull request by epark18**
https://issues.liferay.com/browse/LRAC-8341
https://issues.liferay.com/browse/LRAC-8747 (Refactor ticket)

### CODE REVIEW

**Comment by epark18** [comment]
ci:test:sf

**Comment by alexcandidos** [comment]
Hi @epark18 , this is one of the cases in which we would like to have data from a previous time to validate when applying the time filter. I'm adding the label _acqa_test_automation_test_blocked_. For more information, please see the [slack thread](https://liferay.slack.com/archives/C028J6BS3SP/p1628811523143200).

**Comment by epark18** [comment]
ci:test:sf

**Comment by epark18** [comment]
@alexcandidos I have made some changes, quarantined the test, and added a refactor ticket.

**Comment by alexcandidos** [comment]
hi @epark18 , thanks for the adjustments!

I'm forwarding it.

**Comment by alexcandidos** [comment]
ci:forward

**Pull request closed without merging**
