### PR TITLE
LRAC-10000 Add dismissOnboardingModal

### PR DESCRIPTION
**Pull request by alexcandidos**

### CODE REVIEW

**Comment by alexcandidos** [comment]
ci:test:analytics-cloud:nocompile

**Review by ViniLopes20 — APPROVED** [review]

**Review by manuferreira — APPROVED** [review]

**Comment by AfonsoHSantos** [comment]
Hi @alexcandidos , Thanks for working on it!

The code looks good to me!

**Review by AfonsoHSantos — APPROVED** [review]

**Comment by ViniLopes20** [comment]
Hi @alexcandidos , Thanks for working on it!

The code looks good to me!

**Review by joshitagaki — APPROVED** [review]

**Comment by manuferreira** [comment]
Hi @alexcandidos  , Thanks for working on it!

The code looks good to me!

**Comment by alexcandidos** [comment]
hi guys, I was using the token path `//input` as a way to detect the modal screen, but we have other `//input` available on the AC main dashboard screen, so almost all the cases were failing to try to click on the close button since the if the clause was ` true`.  I'm glad I ran the tests before forwarding ;)

**Comment by alexcandidos** [comment]
ci:test:analytics-cloud:nocompile

**Comment by alexcandidos** [comment]
ci:forward

**Pull request closed without merging**
