### PR TITLE
LRAC-8706, LRAC-8707 | master

### PR DESCRIPTION
**Pull request by Tim-Cao**
https://issues.liferay.com/browse/LRAC-8706
https://issues.liferay.com/browse/LRAC-8707

This is only for master.

@alexcandidos

### CODE REVIEW

**Comment by Tim-Cao** [comment]
ci:test:sf

**Review by alexcandidos — COMMENTED** [review]
Hi @Tim-Cao , it is awesome! Thanks for investigating and implemented our first tests using BrowserMob functionality!

**Comment by alexcandidos** [comment]
@Tim-Cao , could you please just try to complement this and other tests on this same group to include the validation of the Common property keys:

- dataSourceId: String -> it is the `DXP Instance ID` you can get it under the connected Data Source AC Settings > Data Sources;

- channelId: String -> it is the `Property ID:` you can get it under the connected Property AC Settings > Properties;
- userId: String -> you can validate if it is a non-empty value
- id: String -> you can validate if it is a non-empty value

Thanks!

Please, @christianstokes and @r4ddek complement if you have a better or additional idea for this improvement.

**Comment by alexcandidos** [comment]
ci:foward

**Comment by Tim-Cao** [comment]
ci:forward

**Comment by Tim-Cao** [comment]
> @Tim-Cao , could you please just try to complement this and other tests on this same group to include the validation of the **Common property keys**:
> 
> * dataSourceId: String -> it is the `DXP Instance ID` you can get it under the connected Data Source AC Settings > Data Sources;
> * channelId: String -> it is the `Property ID:` you can get it under the connected Property AC Settings > Properties;
> * userId: String -> you can validate if it is a non-empty value
> * id: String -> you can validate if it is a non-empty value
> 
> For now, I'm forwarding it, so you can just complement it if possible with the suggestions above. If it is not possible, please do the others using the same logic you implemented, it is fine as is Today. Thanks Bro!
> 
> Please, @christianstokes and @r4ddek complement if you have a better or additional idea for this improvement.
> 
> cc: @ViniLopes20

Hi @alexcandidos, it is able to implement. Two things I would like to confirm. What does id value stands for? A namespace?
Could you confirm with your team is there a way to get property ID via headless api or jsonws?

**Pull request closed without merging**
