### PR TITLE
AC Test Fix - LRAC-10770 | master

### PR DESCRIPTION
**Pull request by ViniLopes20**
https://issues.liferay.com/browse/LRAC-10770

Hey guys, I'm not running PR on CI because of the problem to build it

**Solution:**
Looking at the history of the test in CI I noticed that it always fails by the number of the day it is trying to check, that day is always the expected day -1, I think the behavior of the `generateDayMonthAndYearValues` macro in CI getting the date from the build that was started and not from the current day. Our build runs on the UTC day change, so I believe it getting the wrong date for that reason. I switched to using `getCurrentDate` macro, this macro I use in custom event tests and it always worked correctly. I think this may be the solution, but I'll only be able to be sure when we observe its execution in the CI.

### CODE REVIEW

**Comment by ViniLopes20** [comment]
ci:test:sf

**Review by joshitagaki — APPROVED** [review]
Nice. I like that solution, it should work. I think it's tricky with CI since it runs at the end of the day (PDT) and since it takes a while for it to actually start the build it takes the date that the build was first in the queue.

**Review by r4ddek — APPROVED** [review]

**Review by manuferreira — APPROVED** [review]
These date-related tests are tricky, we need to keep an eye on them.

**Comment by ViniLopes20** [comment]
Hi team, Thanks for reviewing!

I'm forwarding it!

**Comment by ViniLopes20** [comment]
ci:forward

**Pull request closed without merging**
