### PR TITLE
AC Automated Test - LRAC-9208, LRAC-9211 | master 

### PR DESCRIPTION
**Pull request by AfonsoHSantos**
https://issues.liferay.com/browse/LRAC-9211
https://issues.liferay.com/browse/LRAC-9208
https://issues.liferay.com/browse/LRAC-9272 (refactor)

### CODE REVIEW

**Comment by AfonsoHSantos** [comment]
ci:test:sf

**Comment by AfonsoHSantos** [comment]
ci:test:sf

**Review by ViniLopes20 — COMMENTED** [review]
hi guys @christianstokes, @joshitagaki, @r4ddek, I think this case is similar to what Alex described here https://github.com/liferay-qa/liferay-portal/pull/957#pullrequestreview-750923810 .

What do you think?

cc: @alexcandidos

**Comment by joshitagaki** [comment]
@ViniLopes20 
Segment by URL is something we should be able to validate the automation. We can grab the URL in DXP where a user has some activities. Referrer might be a bit more difficult to automate. I believe if you navigate between different pages in DXP you'd be able to get a referrer. 
Example: Start off on DXP_page1 go to DXP_page2. DXP_page1 is the referrer

**Comment by AfonsoHSantos** [comment]
Hi @joshitagaki, I tried to follow these steps:

```
1. Connect DXP to AC
2. Add 2 pages
3. Go to page 1
4. Get URL of page 1
5. Go to page 2
6. Add new user
7. Sync new user
8. Login with new user
9. Go to page 1 and 2
10. Close session
11. Go to AC and create the segment
12. Add the Referrer criteria
13. Add the URL of page 1 on criteria
```
But it didn't work.
I tried to create the user first, but it didn't work too.

**Comment by joshitagaki** [comment]
Hi @AfonsoHSantos,
Can you check if pages have synced to AC? Go to AC Sites > Pages. This might not be possible to automate since it'll require Pages to be synced and that can take a while.

**Comment by AfonsoHSantos** [comment]
Hi @joshitagaki , the page isn't synced... Now that you say it, I think that might actually be it.

**Comment by AfonsoHSantos** [comment]
> Hi @joshitagaki , the page isn't synced... Now that you say it, I think that might actually be it.

I added a blog to the page so that it syncs with the AC, and now it works. Should I treat this test as quarantine?

**Comment by joshitagaki** [comment]
@AfonsoHSantos 
Yea I think this is something that could be quarantined. What do you think? @alexcandidos

**Comment by alexcandidos** [comment]
hi @AfonsoHSantos , I think we can update the script according to the steps you had confirmed with @joshitagaki  and we can proceed to add the cases to quarantine tagging the refactor tickets with the `timing` label.

Thanks @joshitagaki !

**Comment by AfonsoHSantos** [comment]
ci:test:sf

**Comment by AfonsoHSantos** [comment]
Hi @alexcandidos, @joshitagaki, @ViniLopes20 , i added the [LRAC-9208](https://github.com/liferay-qa/liferay-portal/pull/970/commits/a6a2d775f103dda39e805e1f4c9e550370bcf6e5) in [quarantine](https://issues.liferay.com/browse/LRAC-9272) and made some adjustments, thanks for the help!

**Comment by alexcandidos** [comment]
Hi @AfonsoHSantos , Thanks for working on it!

The code looks good to me!

I'm forwarding it.

**Comment by alexcandidos** [comment]
ci:forward

**Pull request closed without merging**
