### PR TITLE
LPS-126365

### PR DESCRIPTION
**Pull request by alexcandidos**

### CODE REVIEW

**Comment by Tim-Cao** [comment]
Hi @alexcandidos, this case is already covered by LocalizedNestedFieldsWebContent#DefaultValuesDisplayedForNonTranslatedWebContent

**Comment by emanuelfisilva** [comment]
Thanks for your review @Tim-Cao , but we'll choose to keep these validations separated.

**Comment by Tim-Cao** [comment]
See https://github.com/liferay-echo/liferay-portal/pull/3771
View total diff https://github.com/liferay-echo/liferay-portal/pull/3771/commits/86e8ea5a40f7b4562717369fc74f85df19db2c50

**Comment by Tim-Cao** [comment]
ci:close

**Pull request closed without merging**
