### PR TITLE
AC Test Fix - LRAC-9504 | master

### PR DESCRIPTION
**Pull request by AfonsoHSantos**
https://issues.liferay.com/browse/LRAC-9504 (fix)
https://testray.liferay.com/home/-/testray/case_results?tab=runs&testrayBuildId=1578435155 (run)

### CODE REVIEW

**Comment by AfonsoHSantos** [comment]
ci:test:sf

**Comment by AfonsoHSantos** [comment]
ci:stop

**Comment by AfonsoHSantos** [comment]
ci:stop:sf

**Comment by AfonsoHSantos** [comment]
ci:stop

**Comment by AfonsoHSantos** [comment]
ci:test:sf

**Review by ViniLopes20 — APPROVED** [review]

**Review by manuferreira — APPROVED** [review]

**Comment by alexcandidos** [comment]
Hi @AfonsoHSantos , Thanks for working on it!

The code looks good to me!

I'm forwarding it.

**Comment by alexcandidos** [comment]
ci:forward

**Comment by ViniLopes20** [comment]
ci:forward

**Pull request closed without merging**
