### PR TITLE
AC Test Fix - LRAC-10049 | master 

### PR DESCRIPTION
**Pull request by manuferreira**
I tested it a few times on CI and these 7 tests kept failing, so I will investigate why this is happening, meanwhile I'm sending those who passed.
https://testray.liferay.com/home/-/testray/case_results?testrayBuildId=1604332052&testrayRunId=1604332558 (Testray run)
https://issues.liferay.com/browse/LRAC-8176 (AC Quarantined test list)
https://issues.liferay.com/browse/LRAC-10049 (Bug ticket)

### CODE REVIEW

**Comment by manuferreira** [comment]
ci:test:sf

**Comment by manuferreira** [comment]
ci:test:sf

**Comment by alexcandidos** [comment]
Hi @manuferreira , according to your comment and the testray execution, these 7 tests that are failing should be removed from ignored but should still be in quarantine, right?

so, they should have this property set:

`property portal.upstream = "quarantine";`

- [ ] CanCreateWebBehaviorSegmentUsingEver
- [ ] CanCreateWebBehaviorSegmentViewingWC
- [ ] CanCreateWebBehaviorSegmentUsingOn
- [ ] CanCreateWebBehaviorSegmentUsingBetween
- [ ] CanCreateWebBehaviorSegmentUsingBefore
- [ ] CanCreateWebBehaviorSegmentUsingAfter
- [ ] CanCreateWebBehaviorSegmentCriteriaLeastMostTimes

could you please double-check? I'm seeing you removed the ignore annotation (expected) and the quarantined property (not expected)...

and only the other 4 should be removed from ignored and also removed from quarantine, right? these are right!

- [ ] WebContentTechnologyCardShowsViewsByExpectedDevice
- [ ] WebContentTechnologyCardShowsViewsByExpectedBrowser
- [ ] CanCreateWebBehaviorSegmentSinceXdays
- [ ] AudienceCardShowsExpectedAmountKnowAndAnonymousIndividualsInWC

Thanks!!

**Review by alexcandidos — CHANGES_REQUESTED** [review]
Hi Manu, could you please double-check?

**Comment by manuferreira** [comment]
Yes, I should put them on the quarantine list, I forgot hehe. I'm doing this right now.

**Comment by manuferreira** [comment]
ci:test:sf

**Review by ViniLopes20 — APPROVED** [review]

**Comment by alexcandidos** [comment]
Hi @manuferreira , Thanks for working on it!

The code looks good to me!

I'm forwarding it.

**Comment by alexcandidos** [comment]
ci:forward

**Review by alexcandidos — APPROVED** [review]

**Pull request closed without merging**
