### PR TITLE
AC Automated Test - LRAC-8548, LRAC-8549, LRAC-8550, LRAC-8551, LRAC-8552, LRAC-8553 | master

### PR DESCRIPTION
**Pull request by LucasAcacio**
https://issues.liferay.com/browse/LRAC-8548
https://issues.liferay.com/browse/LRAC-9277 (LRAC-8548 Refactor)
https://issues.liferay.com/browse/LRAC-8549
https://issues.liferay.com/browse/LRAC-9278 (LRAC-8549 Refactor)
https://issues.liferay.com/browse/LRAC-8550
https://issues.liferay.com/browse/LRAC-9279 (LRAC-8550 Refactor)
https://issues.liferay.com/browse/LRAC-8553
https://issues.liferay.com/browse/LRAC-9280 (LRAC-8553 Refactor)
https://issues.liferay.com/browse/LRAC-8551
https://issues.liferay.com/browse/LRAC-9324 (LRAC-8551 Refactor)
https://issues.liferay.com/browse/LRAC-8552
https://issues.liferay.com/browse/LRAC-9323 (LRAC-8552 Refactor)

### CODE REVIEW

**Comment by LucasAcacio** [comment]
ci:test:sf

**Review by alexcandidos — COMMENTED** [review]
hi @christianstokes, @joshitagaki, @r4ddek I would like to check with you guys if you know what we could do on DXP in order to be possible to see a user classified on AC under the following segments.

The cases are related to Organization Attributes with the following properties:

Date Modified
Hierarchy Path
Name
Type

The tests were developed just validating we are able to create segments with these attributes, but I believe it would be good to also validate it working, so, that we are able to see users under these segments.

What do you think?

cc: @ViniLopes20

**Comment by joshitagaki** [comment]
@alexcandidos 
Date modified: I don't think we can automate this at the moment
Hierarchy Path: I'm not too sure how this one works...
Name: It would just be the name of the organization they've created with users that have activity
Type: I only know of the type "Organization" which would show all users in all organizations

**Comment by alexcandidos** [comment]
Thanks for your inputs @joshitagaki !

So, `Name` and `Type as "Organization"` seem to be possible to automate, I mean, generate events under these criteria and have users classifieds...

`Date modified` and `Hierarchy Path` needs clarification ...

@christianstokes @r4ddek what do you guys think?

cc: @ViniLopes20

**Comment by christianstokes** [comment]
@alexcandidos @joshitagaki the hierarchy path is related to parent and child organizations.

So lets say you have parent organization "A" with child organizations "B" and "C" and those organizations also have children "B1" and C1", then the hierarchy path could look like A/B/B1  or A/C or other combinations.

I don't know how useful this is in practice but thats how it works. We may need to check with backend to get the specific details of what values to expect.

Date modified: I am not sure about this one, I think we need to check with someone from backend regarding the best way to test.

**Comment by LucasAcacio** [comment]
ci:test:sf

**Comment by LucasAcacio** [comment]
ci:test:sf

**Comment by alexcandidos** [comment]
We are moving these tests to quarantine since we were not able to determine what are the steps to have it properly tested/automated and two of these `CanCreateSegmentUsingOrganizationPropertyParentOrganization` and `CanCreateSegmentUsingOrganizationPropertyOrganization` are blocked by the bug LRAC-9263. 

Thanks guys!

**Comment by alexcandidos** [comment]
ci:forward

**Pull request closed without merging**
