### PR TITLE
AC Test fix - LRAC-10599 | master

### PR DESCRIPTION
**Pull request by joshitagaki**
Ticket: https://issues.liferay.com/browse/LRAC-10599
Testray: https://testray.liferay.com/home/-/testray/case_results?testrayBuildId=1783476996&testrayRunId=1783529173
The failing cases in testray are due to the master changes with individuals not being able to be synced.
This is part of the larger batches of empty state changes that need to be made.

### CODE REVIEW

**Comment by joshitagaki** [comment]
ci:test:sf

**Review by ViniLopes20 — APPROVED** [review]
LGTM, thanks and good catch to change the tests to use `viewGenericText`

**Review by manuferreira — APPROVED** [review]
LGTM! Thank you Josh :tada:

**Comment by joshitagaki** [comment]
ci:test:sf

**Review by christianstokes — APPROVED** [review]
Approved!

**Comment by christianstokes** [comment]
ci:forward

**Pull request closed without merging**
