### PR TITLE
AC Automated Test - LRAC-8414, LRAC-8415 | Master

### PR DESCRIPTION
**Pull request by Hanlf**
https://issues.liferay.com/browse/LRAC-8414
https://issues.liferay.com/browse/LRAC-8415

For reviewers: `ACNavigation.switchTabInCard()` and `ACAssets.gotoViewsByTechnologyTab()` are somewhat duplicated, I will deal with them in another PR, thanks!

### CODE REVIEW

**Comment by Hanlf** [comment]
ci:test:sf

**Comment by Hanlf** [comment]
ci:test:sf

**Comment by alexcandidos** [comment]
Hi @Hanlf , Thanks for working on it!

The code looks good to me!

I'm forwarding it.

**Comment by alexcandidos** [comment]
ci:forward

**Pull request closed without merging**
