### PR TITLE
LRAC-9179, LRAC-9181 | master

### PR DESCRIPTION
**Pull request by Tim-Cao**
https://issues.liferay.com/browse/LRAC-9179
https://issues.liferay.com/browse/LRAC-9181

This is only for master.

@alexcandidos

There are some changes after run case on local.
Could you double check with team? How does round work? 
If Round up and Round down, the changes PR works.
See https://github.com/liferay-qa/liferay-portal/pull/979/commits/c6c9f3c845b0939d296a49196bc9488f55709b22#diff-b17c2104d0836621034be427a2ca714a30c89a3a16a2cb3c43755cba9db73457R234 and
https://github.com/liferay-qa/liferay-portal/pull/979/commits/c6c9f3c845b0939d296a49196bc9488f55709b22#diff-b17c2104d0836621034be427a2ca714a30c89a3a16a2cb3c43755cba9db73457R381

### CODE REVIEW

**Comment by Tim-Cao** [comment]
ci:test:sf

**Comment by Tim-Cao** [comment]
ci:test:sf

**Comment by alexcandidos** [comment]
hi @Tim-Cao , I believe we should have at least 3,000 Page Views in order to see 1% since 100% is 300,000 and 10 Individuals in order to see 1% since 100% is 1,000. So if the number of page views or individuals is equal or more than these, we probably will get a value different of 0. I think it is why we have always seen it as 0% because the number of interactions during the automation tests is limited/low.

Could you please confirm the behavior @JhonattasFerreira @fcodias ?

cc: @christianstokes

**Comment by Tim-Cao** [comment]
Hi @alexcandidos  the limit of local plan is 110,000 individuals and 75,000,000 page views

**Comment by alexcandidos** [comment]
hi @Tim-Cao , yeah you are right. The plan when running AC locally is Enterprise so the values are higher than on UAT that is on the Basic plan, I'm sorry, my bad.

hi  @JhonattasFerreira @fcodias ? do you know how this round-up works?

**Comment by alexcandidos** [comment]
I'm forwarding your updates Yang!

**Comment by alexcandidos** [comment]
ci:forward

**Pull request closed without merging**
