### PR TITLE
AC Test Fix - LRAC-11034 | master

### PR DESCRIPTION
**Pull request by ViniLopes20**
https://issues.liferay.com/browse/LRAC-11034

ViewPageAddedByDXPDataSource -----(is covered by)------> PagesLis.testcaset#ShowsListOfPages
ViewAssetAddedByDXPDataSource -----(is covered by)------> AssetsBlogs.testcase#ViewAllBlogsShownInAssetList

### CODE REVIEW

**Comment by ViniLopes20** [comment]
ci:test:sf

**Review by manuferreira — APPROVED** [review]
LGTM. Thanks Vini.

**Review by joshitagaki — APPROVED** [review]
Nice catch. LGTM!

**Comment by ViniLopes20** [comment]
Hi team, Thanks for reviewing!

I'm forwarding it!

**Comment by ViniLopes20** [comment]
ci:forward

**Pull request closed without merging**
