### PR TITLE
AC Automated Test - LRAC-8280 | master

### PR DESCRIPTION
**Pull request by manuferreira**
https://issues.liferay.com/browse/LRAC-8280

### CODE REVIEW

**Comment by ViniLopes20** [comment]
ci:test:sf

**Comment by christianstokes** [comment]
@alexcandidos I think the steps look okay. Later we will have to deal with all of the pauses

**Comment by alexcandidos** [comment]
yeah @christianstokes , we will have to refactor the pauses.

Hi @manuferreira , Thanks for working on it!

The code looks good to me!

I'm forwarding it.

**Comment by alexcandidos** [comment]
ci:forward

**Pull request closed without merging**
