### PR TITLE
LRAC-9698 Reduce running time for certain long tests

### PR DESCRIPTION
**Pull request by joshitagaki**
https://issues.liferay.com/browse/LRAC-9698
@alexcandidos isolating more tests that run long

### CODE REVIEW

**Comment by alexcandidos** [comment]
Hi @joshitagaki , Thanks for working on it!

The code looks good to me!

I'm forwarding it.

**Comment by alexcandidos** [comment]
ci:forward

**Comment by joshitagaki** [comment]
Oops let me fix that

**Comment by joshitagaki** [comment]
ci:test:sf

**Comment by joshitagaki** [comment]
ci:forward

**Pull request closed without merging**
