### PR TITLE
AC Test Fix - LRAC-9624 | master

### PR DESCRIPTION
**Pull request by AfonsoHSantos**
https://issues.liferay.com/browse/LRAC-9624 (fix)
https://testray.liferay.com/home/-/testray/case_results?tab=runs&testrayBuildId=1573981683 (run)
afonsohsantos#44

### CODE REVIEW

**Comment by AfonsoHSantos** [comment]
ci:test:sf

**Comment by joshitagaki** [comment]
Looks good! Forwarding

**Comment by joshitagaki** [comment]
ci:forward

**Comment by joshitagaki** [comment]
ci:forward

**Pull request closed without merging**
