### PR TITLE
LPS-126356

### PR DESCRIPTION
**Pull request by alexcandidos**

### CODE REVIEW

**Comment by Tim-Cao** [comment]
Hi @alexcandidos, this case duplicates with LocalizedNestedFieldsWebContent#DefaultTitleIsDisplayedUponLocaleChange  
See https://github.com/liferay-qa/liferay-portal/pull/165

**Review by emanuelfisilva — COMMENTED** [review]
Hey @Tim-Cao , thanks for your review. We will choose to keep this test as per now, and work on refactor it later as per defined strategy.

**Comment by Tim-Cao** [comment]
See https://github.com/liferay-echo/liferay-portal/pull/3707
View total diff https://github.com/liferay-echo/liferay-portal/pull/3707/commits/4d9a348c8816d9a792b88d3dba3a001d9c707823

**Comment by Tim-Cao** [comment]
ci:close

**Pull request closed without merging**
