### PR TITLE
AC Test Fix - LRAC-9317 | master

### PR DESCRIPTION
**Pull request by andreefarias**
https://issues.liferay.com/browse/LRAC-9317 (test fix ticket)
https://github.com/andreefarias/liferay-portal/pull/1

### CODE REVIEW

**Comment by andreefarias** [comment]
ci:test:sf

**Comment by ViniLopes20** [comment]
ci:test:sf

**Comment by ViniLopes20** [comment]
ci:stop:analytics-cloud

**Comment by christianstokes** [comment]
ci:forward

**Pull request closed without merging**
