### PR TITLE
LRAC-8805, LRAC-8806, LRAC-8807, LRAC-8808 | master

### PR DESCRIPTION
**Pull request by Tim-Cao**
https://issues.liferay.com/browse/LRAC-8805
https://issues.liferay.com/browse/LRAC-8806
https://issues.liferay.com/browse/LRAC-8807
https://issues.liferay.com/browse/LRAC-8808

This is only for master.

@alexcandidos

### CODE REVIEW

**Comment by Tim-Cao** [comment]
ci:test:sf

**Comment by Tim-Cao** [comment]
ci:test:sf

**Review by alexcandidos — COMMENTED** [review]
Hi @Tim-Cao , Thanks for working on it!

The code looks good to me!

I'm forwarding it.

**Comment by alexcandidos** [comment]
ci:forward

**Pull request closed without merging**
