### PR TITLE
AC Automated Test - LRAC-10164,LRAC-10165,LRAC-10167,LRAC-10197 and LRAC-10360 | master

### PR DESCRIPTION
**Pull request by ViniLopes20**
https://issues.liferay.com/browse/LRAC-10197
https://issues.liferay.com/browse/LRAC-10164
https://issues.liferay.com/browse/LRAC-10165
https://issues.liferay.com/browse/LRAC-10167
https://issues.liferay.com/browse/LRAC-10360

### CODE REVIEW

**Comment by ViniLopes20** [comment]
ci:test:sf

**Comment by alexcandidos** [comment]
ci:test:sf

**Comment by alexcandidos** [comment]
Hi @ViniLopes20 , Thanks for working on it!

The code looks good to me!

I'm forwarding it.

**Comment by alexcandidos** [comment]
ci:forward

**Pull request closed without merging**
