### PR TITLE
LRAC-8487 | master

### PR DESCRIPTION
**Pull request by brookedalton**
https://issues.liferay.com/browse/LRAC-8487

Hi @alexcandidos, I spoke with Josh and he said that the timing of this test will make it quarantined if we try and implement a hover feature for the membership card graph since the last point on the graph shows yesterdays date and would require a full day before you can actually see when it was added. But he recommended using a static segment for this test to show that the member count had gone down in the legend header. 

I also tried adjusting the steps for the previous tests based on the feedback you gave here: https://github.com/liferay-qa/liferay-portal/pull/775#discussion_r695295950 although I still wasn't able to see the members. Let me know if you'd like me to drop those commits though. 

Thanks!

### CODE REVIEW

**Comment by brookedalton** [comment]
ci:test:sf

**Comment by brookedalton** [comment]
ci:test:sf

**Comment by alexcandidos** [comment]
Hi @brookedalton , Thanks for working on it and for the investigation with @joshitagaki ! 

I see, yeah, I think that we are not able to automate this test right now (_validate the Added/Removed option when hovering the graph_), and the way how we did is different from what the test is expecting, so as we don't have a way to simulate that, I would like to keep this case in quarantine using the ticket you had created for the refactoring (https://issues.liferay.com/browse/LRAC-8887) and we can bring this case to the team soon. If not we'll be validating a different thing.

What do you think @christianstokes ?

**Comment by christianstokes** [comment]
Yeah we don't have a way to test this right now. Because the graph shows changes per day and only goes up to _yesterday's_ changes, the only way to see removed members is like this:

day 1: create a segment and add a member
day 2: remove a member
day 3: view the graph

Since we don't have a way to back fill the data I don't think we can test this right now.

**Comment by alexcandidos** [comment]
hi @brookedalton , could you please update this PR by adding the mentioned test to quarantine too? Thanks and sorry for the inconvenience !

**Comment by alexcandidos** [comment]
I'm closing this PR, the pending work was submitted via https://github.com/liferay-qa/liferay-portal/pull/958

**Pull request closed without merging**
