### PR TITLE
LPS-126439

### PR DESCRIPTION
**Pull request by alexcandidos**

### CODE REVIEW

**Comment by nikki-pru** [comment]
Reviewing

**Comment by nikki-pru** [comment]
@hanlf, this is related to pulls #26 and #27

**Comment by Hanlf** [comment]
Hi @nikki-pru , Thank you for your reminder, I plan to review all the pulls about color, just left a comment under these pulls.

**Comment by Hanlf** [comment]
Pull sent here: https://github.com/david-gutierrez-mesa/liferay-portal/pull/75

**Pull request closed without merging**
