### PR TITLE
AC Automated Test - LRAC-8470 | master

### PR DESCRIPTION
**Pull request by kenduenwald**
https://issues.liferay.com/browse/LRAC-8470
https://issues.liferay.com/browse/LRAC-8510
https://issues.liferay.com/browse/LRAC-8511
https://issues.liferay.com/browse/LRAC-8512
https://issues.liferay.com/browse/LRAC-8513
https://issues.liferay.com/browse/LRAC-8519
https://issues.liferay.com/browse/LRAC-8521
https://issues.liferay.com/browse/LRAC-8522
https://issues.liferay.com/browse/LRAC-8523
https://issues.liferay.com/browse/LRAC-8524
https://issues.liferay.com/browse/LRAC-8525

### CODE REVIEW

**Comment by kenduenwald** [comment]
ci:test:sf

**Comment by alexcandidos** [comment]
reviewing...

**Comment by alexcandidos** [comment]
Hi @kenduenwald , Thanks for working on it!

The code looks good to me!

I'm forwarding it.

**Comment by alexcandidos** [comment]
ci:forward

**Pull request closed without merging**
