### PR TITLE
LPS-126854

### PR DESCRIPTION
**Pull request by alexcandidos**

### CODE REVIEW

**Comment by joshchong** [comment]
The steps in this test are already covered by DMRichTextField#SetHelpTextOfRichText in (PR https://github.com/liferay-qa/liferay-portal/pull/134)

**Comment by emanuelfisilva** [comment]
Hey @joshchong , thanks pointing this out. 
I can see the intersection where both tests validate the HelpText of the field, but as a decision, each of these tests would single validate a property (but in the case of the test that validates both, we wouldn't reprove it for that reason). 
So we prefer to accept both of them, and on a future effort, refactor it to reach the better way.

**Comment by joshchong** [comment]
Got it @emanuelfisilva thanks for the clarification! I'll be forwarding this PR then.

**Comment by joshchong** [comment]
Made changes and forwarded to https://github.com/austinchiang/liferay-portal/pull/949

**Pull request closed without merging**
