### PR TITLE
AC Test Fix - LRAC-10996 | master

### PR DESCRIPTION
**Pull request by joshitagaki**
https://issues.liferay.com/browse/LRAC-10996
[Testray](https://testray.liferay.com/home/-/testray/case_results?testrayBuildId=1695063104&testrayRunId=1695078017)

### CODE REVIEW

**Comment by joshitagaki** [comment]
ci:test:sf

**Review by manuferreira — APPROVED** [review]
LGTM, thanks Josh :grin:

**Review by christianstokes — APPROVED** [review]
Looks good, thank you.

**Comment by christianstokes** [comment]
ci:forward

**Pull request closed without merging**
