### PR TITLE
AC Automated Test - LRAC-10194,LRAC-10195,LRAC-10196 and LRAC-10148 | master

### PR DESCRIPTION
**Pull request by ViniLopes20**
https://issues.liferay.com/browse/LRAC-10148
https://issues.liferay.com/browse/LRAC-10194
https://issues.liferay.com/browse/LRAC-10195
https://issues.liferay.com/browse/LRAC-10196

### CODE REVIEW

**Comment by ViniLopes20** [comment]
ci:test:sf

**Comment by alexcandidos** [comment]
Hi @ViniLopes20 , Thanks for working on it!

The code looks good to me!

I'm forwarding it.

**Comment by alexcandidos** [comment]
ci:forward

**Comment by ViniLopes20** [comment]
ci:forward

**Comment by alexcandidos** [comment]
ci:forward

**Pull request closed without merging**
