### PR TITLE
AC Test Property Update - LRAC-11026 | master

### PR DESCRIPTION
**Pull request by christianstokes**
https://issues.liferay.com/browse/LRAC-11026

Based on the changes here:
https://github.com/michaelhashimoto/liferay-portal/pull/2300

### CODE REVIEW

**Review by joshitagaki — APPROVED** [review]
LGTM

**Review by calvinctvo — APPROVED** [review]
The code LGTM! Thank you for your explanation @christianstokes

**Comment by christianstokes** [comment]
ci:test:sf

**Comment by christianstokes** [comment]
ci:test:sf

**Comment by christianstokes** [comment]
ci:forward

**Pull request closed without merging**
