### PR TITLE
LRAC-8473, LRAC-8482 | master

### PR DESCRIPTION
**Pull request by Tim-Cao**
https://issues.liferay.com/browse/LRAC-8473
https://issues.liferay.com/browse/LRAC-8482

This is only for master.

@alexcandidos

### CODE REVIEW

**Comment by Tim-Cao** [comment]
ci:test:sf

**Comment by Tim-Cao** [comment]
ci:test:sf

**Comment by Tim-Cao** [comment]
ci:test:sf

**Comment by Tim-Cao** [comment]
ci:test:sf

**Comment by alexcandidos** [comment]
Hi @Tim-Cao  , Thanks for working on it!

The code looks good to me!

I just rebased and sent it again to solve some conflicts via #679 .

Thanks!

**Pull request closed without merging**
