### PR TITLE
LRAC-8799, LRAC-8800, LRAC-8801, LRAC-8802, LRAC-8804, LRAC-8869, LRAC-8870 | master

### PR DESCRIPTION
**Pull request by Tim-Cao**
https://issues.liferay.com/browse/LRAC-8799
https://issues.liferay.com/browse/LRAC-8800
https://issues.liferay.com/browse/LRAC-8801
https://issues.liferay.com/browse/LRAC-8802
https://issues.liferay.com/browse/LRAC-8804
https://issues.liferay.com/browse/LRAC-8869
https://issues.liferay.com/browse/LRAC-8870

This is only for master.

@alexcandidos

### CODE REVIEW

**Comment by Tim-Cao** [comment]
ci:test:sf

**Comment by Tim-Cao** [comment]
ci:test:sf

**Comment by Tim-Cao** [comment]
ci:test:sf

**Comment by alexcandidos** [comment]
Hi @Tim-Cao , Thanks for working on it!

The code looks good to me!

I'm forwarding it.

**Comment by alexcandidos** [comment]
ci:forward

**Pull request closed without merging**
