### PR TITLE
AC Automated Test - LRAC-10727 | master 

### PR DESCRIPTION
**Pull request by manuferreira**
https://issues.liferay.com/browse/LRAC-10727 (ticket)
https://issues.liferay.com/browse/LRAC-9248 (Story)

### CODE REVIEW

**Comment by manuferreira** [comment]
ci:test:sf

**Comment by manuferreira** [comment]
ci:test:sf

**Comment by manuferreira** [comment]
ci:test:sf

**Review by r4ddek — APPROVED** [review]
Very nice, thanks Manussa ❤️

**Review by ViniLopes20 — APPROVED** [review]
Your code is very good, @manuferreira. I liked the organization. Very good job! 😄

**Review by christianstokes — APPROVED** [review]
Looks great!

**Comment by christianstokes** [comment]
ci:forward

**Pull request closed without merging**
