### PR TITLE
AC Automated Test - LRAC-11055 | master

### PR DESCRIPTION
**Pull request by ViniLopes20**
https://issues.liferay.com/browse/LRAC-11055
[Testray](https://testray.liferay.com/home/-/testray/case_results/1741851997?redirect=https%3A%2F%2Ftestray.liferay.com%2Fhome%2F-%2Ftestray%2Fcase_results%2Findex%3FtestrayCaseName%3DDeletedPropertiesNotAppearAsOptionInSyncSites%26testrayBuildId%3D1741838604%26cur%3D1%26delta%3D200%26orderByCol%3Dstatus_sortable%26orderByType%3Dasc)
https://issues.liferay.com/browse/LRAC-10602 (bug)

### CODE REVIEW

**Comment by ViniLopes20** [comment]
ci:test:sf

**Review by christianstokes — APPROVED** [review]
Looks good Vini!

**Review by manuferreira — APPROVED** [review]
LGTM! Thank you :police_officer:

**Comment by christianstokes** [comment]
ci:forward

**Pull request closed without merging**
