### PR TITLE
AC Test Fix - LRAC-9463 | master

### PR DESCRIPTION
**Pull request by AfonsoHSantos**
https://issues.liferay.com/browse/LRAC-9463 (fix)
[afonsohsantos#28](https://github.com/AfonsoHSantos/liferay-portal/pull/28)
https://testray.liferay.com/home/-/testray/case_results?tab=runs&testrayBuildId=1565777490 (run)

### CODE REVIEW

**Comment by AfonsoHSantos** [comment]
ci:test:sf

**Comment by AfonsoHSantos** [comment]
ci:test:sf

**Comment by AfonsoHSantos** [comment]
ci:test:sf

**Comment by christianstokes** [comment]
ci:forward

**Pull request closed without merging**
