### PR TITLE
AC Test Fix - LRAC-10768 | master

### PR DESCRIPTION
**Pull request by ViniLopes20**
https://issues.liferay.com/browse/LRAC-10768

Hey guys, I'm not running PR on CI because of the problem to build it

### CODE REVIEW

**Comment by ViniLopes20** [comment]
ci:test:sf

**Review by christianstokes — APPROVED** [review]
Using generic macros. 👏
Looks good.

**Review by joshitagaki — APPROVED** [review]
Looks good to me

**Review by manuferreira — APPROVED** [review]
Thanks Vini :D

**Review by r4ddek — APPROVED** [review]

**Comment by ViniLopes20** [comment]
Hi team, Thanks for reviewing!

I'm forwarding it!

**Comment by ViniLopes20** [comment]
ci:forward

**Comment by ViniLopes20** [comment]
ci:forward

**Comment by ViniLopes20** [comment]
ci:forward

**Pull request closed without merging**
