### PR TITLE
Remove test to acceptance - LRAC-11009 | master

### PR DESCRIPTION
**Pull request by ViniLopes20**
https://issues.liferay.com/browse/LRAC-11009

After this [PR](https://github.com/liferay/com-liferay-osb-faro-private/pull/4145) is merged `ShowsSitesTopInterests` will be failing, so to not be failing in the PR of the devs, let's remove it from acceptance and put it after making changes of [LRAC-10405](https://issues.liferay.com/browse/LRAC-10405)

### CODE REVIEW

**Review by joshitagaki — APPROVED** [review]
LGTM

**Review by manuferreira — APPROVED** [review]
Nice, thanks Vini :police_officer:

**Review by christianstokes — APPROVED** [review]
Approved

**Comment by christianstokes** [comment]
ci:forward

**Pull request closed without merging**
