### PR TITLE
LPS-126401

### PR DESCRIPTION
**Pull request by alexcandidos**

### CODE REVIEW

**Comment by Tim-Cao** [comment]
Hi @alexcandidos, this case is already covered by LocalizedSimpleFieldsWebContent#TranslationsRemainsUponSavingWebContent

**Review by emanuelfisilva — COMMENTED** [review]
Hey @Tim-Cao , thanks for your review. We will choose to keep this test as per now, and work on refactor it later as per defined strategy.

**Comment by Tim-Cao** [comment]
See https://github.com/liferay-echo/liferay-portal/pull/3705
View total diff https://github.com/liferay-echo/liferay-portal/pull/3705/commits/8c903c71f88daf5df2707cf24a680083c1fb2f65

**Comment by Tim-Cao** [comment]
ci:close

**Pull request closed without merging**
