### PR TITLE
LRAC-9146, LRAC-9147, LRAC-9149, LRAC-9150 | master

### PR DESCRIPTION
**Pull request by Tim-Cao**
https://issues.liferay.com/browse/LRAC-9146
https://issues.liferay.com/browse/LRAC-9147
https://issues.liferay.com/browse/LRAC-9149
https://issues.liferay.com/browse/LRAC-9150

This is only for master.

@alexcandidos

### CODE REVIEW

**Comment by Tim-Cao** [comment]
ci:test:sf

**Comment by Tim-Cao** [comment]
ci:test:sf

**Comment by Tim-Cao** [comment]
ci:test:sf

**Comment by alexcandidos** [comment]
Hi @Tim-Cao , Thanks for working on it!

The code looks good to me!

Could you please just solve the conflicts in order to proceed to forward it?

Thanks!

**Comment by Tim-Cao** [comment]
ci:forward

**Pull request closed without merging**
