### PR TITLE
Enable AC Test - LRAC-8176 | master

### PR DESCRIPTION
**Pull request by manuferreira**
https://testray.liferay.com/home/-/testray/case_results/1616460727/history?tab=result&hideFilterPin=true
https://testray.liferay.com/home/-/testray/case_results/1616460693/history?tab=result&hideFilterPin=true
https://testray.liferay.com/home/-/testray/case_results/1616460668/history?tab=result&hideFilterPin=true
https://testray.liferay.com/home/-/testray/case_results/1616460747/history?tab=result&hideFilterPin=true
https://testray.liferay.com/home/-/testray/case_results/1616460676/history?tab=result&hideFilterPin=true

### CODE REVIEW

**Comment by manuferreira** [comment]
ci:test:sf

**Review by ViniLopes20 — APPROVED** [review]

**Comment by alexcandidos** [comment]
Hi @manuferreira , Thanks for working on it!

The code looks good to me!

I'm forwarding it.

**Comment by alexcandidos** [comment]
hey @manuferreira  and @ViniLopes20 , just one thing, I saw some warnings are happening during the test execution, it would be good to look at the logs to see what could be happening... Thanks, team!

LocalFile_CustomEventsChangeDataType_CanChangeDataTypeFromFilter

**Review by alexcandidos — APPROVED** [review]

**Comment by alexcandidos** [comment]
ci:forward

**Pull request closed without merging**
