### PR TITLE
AC Automated Test - LRAC-8436, LRAC-8445, LRAC-8446, LRAC-8444, LRAC-8443 | master

### PR DESCRIPTION
**Pull request by catarineaguiar**
https://issues.liferay.com/browse/LRAC-8436
https://issues.liferay.com/browse/LRAC-8445
https://issues.liferay.com/browse/LRAC-8446
https://issues.liferay.com/browse/LRAC-8444
https://issues.liferay.com/browse/LRAC-8443

Refactor tickets:
https://issues.liferay.com/browse/LRAC-8861 
https://issues.liferay.com/browse/LRAC-8860
https://issues.liferay.com/browse/LRAC-8817
https://issues.liferay.com/browse/LRAC-8865

### CODE REVIEW

**Comment by ViniLopes20** [comment]
ci:test:sf

**Comment by alexcandidos** [comment]
hi @catarineaguiar , could you please review what is missing on poshi code?
The sf check says: 
```
Missing child elements
     [exec] /opt/dev/projects/github/liferay-portal/portal-web/test/functional/com/liferay/portalweb/tests/enduser/analyticscloud/AssetsWebContent.testcase:274
```

**Comment by catarineaguiar** [comment]
ci:test:sf

**Comment by ViniLopes20** [comment]
ci:test:sf

**Comment by alexcandidos** [comment]
Hi @catarineaguiar , Thanks for working on it!

The code looks good to me!

I'm forwarding it.

**Comment by alexcandidos** [comment]
ci:forward

**Pull request closed without merging**
