### PR TITLE
AC Disable/Quarantined Test - LRAC-10769 | master

### PR DESCRIPTION
**Pull request by ViniLopes20**
This is the ticket to investigate and fix test issues and take them out of quarantine in the future. These tests are constantly failing, so let's quarantine them to avoid known/expected errors in the master/release routine

https://issues.liferay.com/browse/LRAC-10769
https://issues.liferay.com/browse/LRAC-10527
https://issues.liferay.com/browse/LRAC-10599
https://issues.liferay.com/browse/LRAC-10024

### CODE REVIEW

**Comment by ViniLopes20** [comment]
ci:test:sf

**Review by joshitagaki — APPROVED** [review]
LGTM!

**Comment by ViniLopes20** [comment]
Hi team, Thanks for reviewing!

I'm forwarding it!

**Comment by ViniLopes20** [comment]
ci:forward

**Pull request closed without merging**
