### PR TITLE
AC Automated Test - LRAC-9204 | master

### PR DESCRIPTION
**Pull request by 91nilo**
https://issues.liferay.com/browse/LRAC-9204
https://issues.liferay.com/browse/LRAC-9264 (Refactor)

### CODE REVIEW

**Comment by 91nilo** [comment]
ci:test:sf

**Review by ViniLopes20 — COMMENTED** [review]
hi guys @christianstokes, @joshitagaki, @r4ddek, I think this case is similar to what Alex described here https://github.com/liferay-qa/liferay-portal/pull/957#pullrequestreview-750923810 .

What do you think?

cc: @alexcandidos

**Comment by alexcandidos** [comment]
hi @ViniLopes20 , I think in this case we are able to make a full validation (_including asserting users are classified in this segment_) since the DXP interaction we make should be considered as "Desktop", we'll be only pending different cases like "Mobile" for this we can create a new test on the test map to test manually while we don't have a way to automate/simulate this kind of interaction right now.

what do you think?

**Comment by alexcandidos** [comment]
hi @91nilo , could you please try to implement the missing steps? In this case, we would like to make some interactions with that user on DXP and then validate we are able to see a user classified according to this segment criteria. Thanks!

**Comment by 91nilo** [comment]
ci:test:sf

**Comment by 91nilo** [comment]
Hi @alexcandidos i did the requested changes, also i had issues on the dynamic segment "total members" and "known members" chart data, so the quarantine label and refactor ticket number has been added.
Thank you, if there is anything else i could do to improve this code, just let me know.

**Comment by alexcandidos** [comment]
Hi @91nilo , Thanks for working on it!

The code looks good to me!

I'm forwarding it.

**Comment by alexcandidos** [comment]
ci:forward

**Pull request closed without merging**
