### PR TITLE
LPS-126372

### PR DESCRIPTION
**Pull request by alexcandidos**

### CODE REVIEW

**Comment by Tim-Cao** [comment]
Hi @alexcandidos, this case duplicates with LocalizedNestedFieldsStructure#TranslationDoesNotChangeAnother

**Comment by emanuelfisilva** [comment]
Hey @Tim-Cao , thanks for your review. We will choose to keep this test as per now, and work on refactor it later as per defined strategy.

**Comment by Tim-Cao** [comment]
See https://github.com/liferay-echo/liferay-portal/pull/3706
View total diff https://github.com/liferay-echo/liferay-portal/pull/3706/commits/f4dbbf8663b0e00dce91bf35b1f4b82e896b0e25

**Comment by Tim-Cao** [comment]
ci:close

**Pull request closed without merging**
