### PR TITLE
AC Test Fix - LRAC-10997 | master

### PR DESCRIPTION
**Pull request by ViniLopes20**
https://issues.liferay.com/browse/LRAC-10997
[Testray](https://testray.liferay.com/home/-/testray/case_results/index?p_p_state=normal&orderByCol=status_sortable&orderByType=asc&testrayBuildId=1703345185)

### CODE REVIEW

**Review by joshitagaki — APPROVED** [review]
LGTM!

**Review by christianstokes — APPROVED** [review]
Approved

**Comment by christianstokes** [comment]
ci:forward

**Review by manuferreira — COMMENTED** [review]
LGTM!

**Pull request closed without merging**
