### PR TITLE
AC Test Fix - LRAC-9646 | master 

### PR DESCRIPTION
**Pull request by manuferreira**
https://issues.liferay.com/browse/LRAC-9646 (bug ticket)

### CODE REVIEW

**Comment by manuferreira** [comment]
I tested this case automatically and It did pass, but I noticed that it should appear some interest of the user in his profile page (since he views a page), I'm seeing that this data will take some time to show up. I think it does not make sense take the "ignore" of this test because, if the interest of the user take some time to appear, does still make sense search for a nonexistent interest (even if the list of interests it's empty)?
What do you guys think @alexcandidos, @ViniLopes20, @AfonsoHSantos?

**Comment by manuferreira** [comment]
ci:test:sf

**Review by ViniLopes20 — APPROVED** [review]
Yes @manuferreira, it doesn't make sense for the test to run and pass the CI since it will go through the fact that the list of interests doesn't have any data and not because it hasn't found the interest that doesn't exist in the list, that way it can passing a bug.

**Comment by alexcandidos** [comment]
I agree with you @manuferreira !

**Comment by alexcandidos** [comment]
Hi @manuferreira , Thanks for working on it!

The code looks good to me!

I'm forwarding it.

**Comment by alexcandidos** [comment]
ci:forward

**Pull request closed without merging**
