### PR TITLE
AC Automated Test - LRAC-8625 | master

### PR DESCRIPTION
**Pull request by alessandromalves**
https://issues.liferay.com/browse/LRAC-8625

### CODE REVIEW

**Comment by alessandromalves** [comment]
ci:test:sf

**Comment by alessandromalves** [comment]
ci:test:sf

**Comment by alexcandidos** [comment]
Hi @alessandromalves , Thanks for working on it!

The code looks good to me!

I'm forwarding it.

**Comment by alexcandidos** [comment]
ci:forward

**Pull request closed without merging**
