### PR TITLE
AC Automated Test - LRAC-8793 | master

### PR DESCRIPTION
**Pull request by MathausC**
https://issues.liferay.com/browse/LRAC-8793
https://github.com/liferay-qa/liferay-portal/pull/849
Update of some macros.

### CODE REVIEW

**Comment by MathausC** [comment]
ci:test:sf

**Comment by MathausC** [comment]
ci:test:sf

**Comment by alexcandidos** [comment]
Hi @MathausC , thanks for working on it!

**Comment by alexcandidos** [comment]
ci:forward

**Pull request closed without merging**
