### PR TITLE
Isolate aborted tests to own batch - LRAC-10974 | master 

### PR DESCRIPTION
**Pull request by joshitagaki**
https://issues.liferay.com/browse/LRAC-10974

### CODE REVIEW

**Comment by joshitagaki** [comment]
ci:test:sf

**Review by ViniLopes20 — APPROVED** [review]
LGTM

**Review by manuferreira — APPROVED** [review]
LGTM, thanks Josh.

**Review by christianstokes — APPROVED** [review]

**Comment by christianstokes** [comment]
ci:forward

**Pull request closed without merging**
