### PR TITLE
AC Test Fix - LRAC-9350 | master 

### PR DESCRIPTION
**Pull request by manuferreira**
https://testray.liferay.com/home/-/testray/case_results?testrayBuildId=1632859286&testrayRunId=1632866209 (Testray run for `DeleteSegments#DeleteCustomFieldUsedSegmentResetData`)
https://testray.liferay.com/home/-/testray/case_results?testrayBuildId=1632044387&testrayRunId=1632045025 (Testray run for `SegmentsCreationIndividualAttributes#CanAddSegmentWithCustomFieldsForIndividuals`)
https://issues.liferay.com/browse/LRAC-9350 (bug)

### CODE REVIEW

**Comment by manuferreira** [comment]
ci:test:sf

**Comment by manuferreira** [comment]
I'm just removing the bug related message and keeping these tests with the `ignore` property because both of them are related to our Personas approach.
@alexcandidos @ViniLopes20 @r4ddek

**Comment by manuferreira** [comment]
ci:test:sf

**Comment by manuferreira** [comment]
Hey guys, I talked to Leo and Vini and we saw that these tests won't be able to participate in the personas approach.
When we create a custom field in DXP via automation, the custom field does not seem to appear in AC, but it does appear only when we do in an manual way. I did some digging and it seems that when we create the custom field and later on we edit again and then we synchronize it appears in AC. That's why I repeated this one step in these two tests, it's a bit odd but it's working.

And the other thing is I changed some steps in this case `DeleteCustomFieldUsedSegmentResetData` because I saw that we wouldn't be able to make this check because we have to wait at least a day for the data in the segment to show up and also this case depends on a custom field in DXP, one thing I did was to check the presence of the individuals through the segment preview.
What do you guys think?

**Review by alexcandidos — APPROVED** [review]
Hi @manuferreira , Thanks for working on it!

The code looks good to me!

I'm forwarding it.

**Comment by alexcandidos** [comment]
ci:forward

**Pull request closed without merging**
