### PR TITLE
LRCI-2150 Remove usages of MetalComponent.macro in liferay-portal tests 7.3+

### PR DESCRIPTION
**Pull request by kenjiheigel**
https://issues.liferay.com/browse/LRCI-2150

@john-co, @kyle-miho, or @vicnate5 could one of you guys help to do a final review on this? @Tim-Cao helped work on this to help reduce pauses in the tests related to the now defunct MetalComponent.macro. Overall, saves at least 68 hours of server time from upstream builds (for context, total server time is ~70 days for that build), and saves at least 10 hours of server time from acceptance builds (total server time is ~13 days). Also shaves off ~3 minutes from PortalSmoke#Smoke (without these changes, it takes ~8 minutes). 

Here is the comparison against upstream on testray: https://testray.liferay.com/home/-/testray/runs/compare?formDate=1620240771953&testrayRunIdA=1530416354&testrayRunIdB=1530501713

Additionally, here's some of the time data I put together:
https://docs.google.com/spreadsheets/d/1AL0di1_r-hsqLMeAovjvYeEK1UgNPO3r2DzYfqVM4fU/edit#gid=0

### CODE REVIEW

**Comment by kyle-miho** [comment]
https://testray.liferay.com/home/-/testray/runs/compare?compare=true&view=details&statusA=2&testrayRunIdB=1530501713&testrayRunIdA=1530416354&testrayTeamId=1310723367&statusB=3
There seem to be a decent amount of Collab unique failures (~15), although im not sure how it can be related to this change:
@kenjiheigel i'm not sure what the new poshi function does, does it interact with this at all in the selenium layer? maybe it timed out
     [exec]     Timed out after 180 seconds while executing waitForJavaScriptNoError
     [exec] 
     [exec]     BUILD FAILED: An error occurred while executing waitForJavaScriptNoError
     [exec]     /opt/dev/projects/github/liferay-portal/portal-web/test/functional/com/liferay/portalweb/tests/enduser/documentmanagement/externalvideoshortcut/VideoShortcut.testcase[AddWCWithEmbeddedVideo]:386
     
 But regardless of these unique failures, since it was a gauntlet run, personally I think its still worth pushing it in since almost all of the tests are still passing regardless of this PR, the performance improvement is worth a small amount of tests to fix later

**Comment by vicnate5** [comment]
Need to make sure this doesn't break the baseline relevant tests before pushing. We would need to quarantine tests in that layer if we want to fix later.

**Comment by Tim-Cao** [comment]
> https://testray.liferay.com/home/-/testray/runs/compare?compare=true&view=details&statusA=2&testrayRunIdB=1530501713&testrayRunIdA=1530416354&testrayTeamId=1310723367&statusB=3
> There seem to be a decent amount of Collab unique failures (~15), although im not sure how it can be related to this change:
> @kenjiheigel i'm not sure what the new poshi function does, does it interact with this at all in the selenium layer? maybe it timed out
> [exec] Timed out after 180 seconds while executing waitForJavaScriptNoError
> [exec]
> [exec] BUILD FAILED: An error occurred while executing waitForJavaScriptNoError
> [exec] /opt/dev/projects/github/liferay-portal/portal-web/test/functional/com/liferay/portalweb/tests/enduser/documentmanagement/externalvideoshortcut/VideoShortcut.testcase[AddWCWithEmbeddedVideo]:386
> 
> But regardless of these unique failures, since it was a gauntlet run, personally I think its still worth pushing it in since almost all of the tests are still passing regardless of this PR, the performance improvement is worth a small amount of tests to fix later

This issue didn't happens on the previous run. See
https://github.com/liferay-qa/liferay-portal/pull/403#issuecomment-833008663
It might be a flaky failure?

**Comment by kenjiheigel** [comment]
@vicnate5, we ran it against the `acceptance-functional` tests here:
https://github.com/kenjiheigel/liferay-portal/pull/789#issuecomment-824113989

That was two weeks ago though, so maybe we can run it again.

**Comment by vicnate5** [comment]
ci:test:relevant

**Comment by kenjiheigel** [comment]
ci:test:relevant

**Comment by kenjiheigel** [comment]
@vicnate5 , can you make the liferay-qa Liferay Inc. membership public? 
image

**Comment by vicnate5** [comment]
@kenjiheigel Not sure who owns this repo, but for now I sent this to my repo.
https://github.com/vicnate5/liferay-portal/pull/1731

After we finish our review, can I push this?

**Comment by vicnate5** [comment]
@kenjiheigel Membership is now public

**Comment by kenjiheigel** [comment]
@vicnate5, yes please! 

I'm gonna close this one then and you can finish review from your pull.

**Pull request closed without merging**
