### PR TITLE
LPS-126430

### PR DESCRIPTION
**Pull request by alexcandidos**

### CODE REVIEW

**Comment by Hanlf** [comment]
Reviewing...

**Comment by nikki-pru** [comment]
Reviewing

**Comment by nikki-pru** [comment]
Oh sorry, @Hanlf , I didn't see your comment before taking this. Go ahead and review this one.

**Comment by Hanlf** [comment]
Pull sent here: https://github.com/david-gutierrez-mesa/liferay-portal/pull/75

**Pull request closed without merging**
