### PR TITLE
AC Automated Test - LRAC-8298 | master

### PR DESCRIPTION
**Pull request by DebSouza**
https://issues.liferay.com/browse/LRAC-8298

### CODE REVIEW

**Comment by ViniLopes20** [comment]
ci:test:sf

**Comment by christianstokes** [comment]
@alexcandidos steps look good.

**Comment by alexcandidos** [comment]
Thanks for reviewing @christianstokes !

Hi @DebSouza , Thanks for working on it!

The code looks good to me!

I'm forwarding it.

**Comment by alexcandidos** [comment]
ci:forward

**Pull request closed without merging**
