### PR TITLE
AC Test Fix - LRAC-7890, LRAC-8176 | master  

### PR DESCRIPTION
**Pull request by manuferreira**
https://issues.liferay.com/browse/LRAC-7890 (Bug ticket)
https://issues.liferay.com/browse/LRAC-8176 (Quarantined tests list)
https://issues.liferay.com/browse/LRAC-9808 (Ticket of the test removed from quarantine)

### CODE REVIEW

**Comment by manuferreira** [comment]
ci:test:sf

**Comment by alexcandidos** [comment]
Hi @manuferreira , Thanks for working on it!

The code looks good to me!

I'm forwarding it.

**Comment by alexcandidos** [comment]
hi @manuferreira , could you please update this tc `ViewAllDocumentsAndMediaShownInAssetList` in our Test Map from `Quarantined` to `Ready` on the column P - `Test Status`?

Thanks!!

**Comment by alexcandidos** [comment]
ci:forward

**Pull request closed without merging**
