### PR TITLE
AC Automated Test - LRAC-8279, LRAC-8282 | master

### PR DESCRIPTION
**Pull request by LucasMonteiro10**
https://issues.liferay.com/browse/LRAC-8279
https://issues.liferay.com/browse/LRAC-8282

### CODE REVIEW

**Comment by alexcandidos** [comment]
ci:test:sf

**Comment by alexcandidos** [comment]
ci:test:sf

**Comment by ViniLopes20** [comment]
ci:test:sf

**Review by alexcandidos — COMMENTED** [review]
Hi @LucasMonteiro10 , Thanks for working on it!

The code looks good to me!

I'm forwarding it.

**Comment by alexcandidos** [comment]
ci:forward

**Pull request closed without merging**
