### PR TITLE
AC Automated Test - LRAC-8493 | master

### PR DESCRIPTION
**Pull request by MathausC**
https://issues.liferay.com/browse/LRAC-8493
https://issues.liferay.com/browse/LRAC-9337 (Refactor ticket)
https://issues.liferay.com/browse/LRAC-9056 (Bug ticket)

### CODE REVIEW

**Comment by MathausC** [comment]
ci:test:sf

**Comment by MathausC** [comment]
ci:test:sf

**Comment by MathausC** [comment]
ci:test:sf

**Comment by ViniLopes20** [comment]
Hi @MathausC, I wanted to ask you two things:

1.  I think you forgot to put the refactor ticket in your test  `// AC Refactor Ticket: LRAC-9337`
2. You could remove the `ViewSegmentCompositionCardUptadesRealTime` stub since your test covers this one, so you could remove

**Comment by MathausC** [comment]
ci:test:sf

**Comment by alexcandidos** [comment]
Hi @MathausC , Thanks for working on it!

The code looks good to me!

I'm forwarding it.

**Comment by alexcandidos** [comment]
ci:forward

**Pull request closed without merging**
