### PR TITLE
AC Test Fix - LRAC-10813 | master

### PR DESCRIPTION
**Pull request by manuferreira**
https://testray.liferay.com/home/-/testray/case_results?testrayBuildId=1652629369&testrayRunId=1652629400 (Testray run)
https://issues.liferay.com/browse/LRAC-10813 (Ticket)

### CODE REVIEW

**Comment by manuferreira** [comment]
ci:test:sf

**Review by ViniLopes20 — APPROVED** [review]
LGTM

**Comment by christianstokes** [comment]
Looks good!

**Comment by christianstokes** [comment]
ci:forward

**Pull request closed without merging**
