### PR TITLE
LPS-126830

### PR DESCRIPTION
**Pull request by alexcandidos**

### CODE REVIEW

**Comment by austinchiang** [comment]
**Reviewing...** :hourglass_flowing_sand: :sunglasses: :headphones:

**Comment by austinchiang** [comment]
Hey @gustavolimav the test you wrote already exists in master https://github.com/liferay/liferay-portal/blob/4f5dd4c5c07162fa9e76f543b6c908069733a123/modules/apps/data-engine/data-engine-test/src/testFunctional/tests/documentsadministration/fields/DMFieldGroups.testcase#L126. Can you write the proper test and resend? I believe it is `DMFieldGroups#DeleteFieldGroupOnStructure` based on https://issues.liferay.com/browse/LPS-126830. Thanks!

**Comment by gustavolimav** [comment]
Hey @austinchiang the test I sent was `DMFieldGroups#DeleteFieldGroupOnStructure` and not `DMFieldGroups#DeleteNestedFieldGroupOnStructure` which already exists in master. Hey @alexcandidos can you review it to me?

**Comment by alexcandidos** [comment]
hey @gustavolimav , you're right! Your test is `DMFieldGroups#DeleteFieldGroupOnStructure` and it is not in master yet. 
Hey @austinchiang, I'm reopening this PR. Thanks guys! :)

**Comment by austinchiang** [comment]
**Reviewing...** :hourglass_flowing_sand: :sunglasses: :headphones:

**Comment by emanuelfisilva** [comment]
Hey @austinchiang , since you're on PTO, I'm assigning myself to review this issue.

**Comment by emanuelfisilva** [comment]
Hey @gustavolimav , thank you. Please notice that your PR had some issues regarding the modifications you've made on`DataEngineBuilder.path`. Also, your conflict's resolution made changes to `DMFieldGroups#DeleteNestedFieldGroupOnStructure`, I believe that's the reason @austinchiang pointed that test in his review.
Please follow https://github.com/emanuelfisilva/liferay-portal/pull/33 where I'm commiting your code with slight changes.

**Pull request closed without merging**
