### PR TITLE
AC Test Fix - LRAC-10579 | master

### PR DESCRIPTION
**Pull request by joshitagaki**
https://issues.liferay.com/browse/LRAC-10579
https://github.com/joshitagaki/liferay-portal/pull/40
Testray: https://testray.liferay.com/home/-/testray/case_results?testrayBuildId=1611428485

### CODE REVIEW

**Comment by joshitagaki** [comment]
ci:test:sf

**Review by ViniLopes20 — APPROVED** [review]

**Comment by alexcandidos** [comment]
Starting to review! 👨🏽‍💻

**Comment by alexcandidos** [comment]
Hi @joshitagaki , Thanks for working on it!

The code looks good to me!

I'm forwarding it.

**Review by alexcandidos — APPROVED** [review]

**Comment by alexcandidos** [comment]
ci:forward

**Pull request closed without merging**
