### PR TITLE
AC Test Fix - LRAC-10435 | master

### PR DESCRIPTION
**Pull request by ViniLopes20**
https://issues.liferay.com/browse/LRAC-10435
https://testray.liferay.com/home/-/testray/case_results?testrayBuildId=1602097091

### CODE REVIEW

**Comment by ViniLopes20** [comment]
ci:test:sf

**Review by manuferreira — APPROVED** [review]

**Comment by alexcandidos** [comment]
Hi @ViniLopes20 , Thanks for working on it!

The code looks good to me!

I'm forwarding it.

**Comment by alexcandidos** [comment]
ci:forward

**Comment by alexcandidos** [comment]
The only point here is if we are hidden a performance issue due to the number of searches we are doing. But as it is not happening locally (the events are quickly appearing), I think for test purposes it is okay.

**Pull request closed without merging**
