### PR TITLE
AC Test Fix - LRAC-10753 | master

### PR DESCRIPTION
**Pull request by ViniLopes20**
https://issues.liferay.com/browse/LRAC-10753

Hey guys, I'm not running PR on CI because of the problem to build it

### CODE REVIEW

**Comment by ViniLopes20** [comment]
ci:test:sf

**Review by joshitagaki — APPROVED** [review]
Looks good to me

**Review by manuferreira — APPROVED** [review]
looks good, thanks Vini.

**Review by christianstokes — APPROVED** [review]

**Comment by ViniLopes20** [comment]
ci:forward

**Pull request closed without merging**
