### PR TITLE
AC Test Fix - LRAC-9309 | master

### PR DESCRIPTION
**Pull request by MathausC**
https://github.com/MathausC/liferay-portal/pull/1
https://issues.liferay.com/browse/LRAC-9309

### CODE REVIEW

**Comment by MathausC** [comment]
ci:test:sf

**Comment by MathausC** [comment]
ci:test:sf

**Comment by MathausC** [comment]
ci:test:sf

**Comment by MathausC** [comment]
ci:test:sf

**Comment by alexcandidos** [comment]
ci:test:sf

**Comment by MathausC** [comment]
ci:test:sf

**Comment by MathausC** [comment]
ci:test:sf

**Comment by MathausC** [comment]
ci:test:sf

**Comment by christianstokes** [comment]
ci:forward

**Pull request closed without merging**
