### PR TITLE
AC Test Fix - LRAC-10973 | master

### PR DESCRIPTION
**Pull request by ViniLopes20**
https://issues.liferay.com/browse/LRAC-10973
[Testray](https://testray.liferay.com/home/-/testray/case_results/index?p_p_state=normal&orderByCol=status_sortable&orderByType=asc&testrayBuildId=1679353933)

### CODE REVIEW

**Comment by ViniLopes20** [comment]
ci:test:sf

**Review by manuferreira — APPROVED** [review]
LGTM, thanks.

**Review by joshitagaki — APPROVED** [review]
LGTM!

**Review by christianstokes — APPROVED** [review]
Looks good!

**Comment by christianstokes** [comment]
ci:forward

**Pull request closed without merging**
