### PR TITLE
Disabled AC Test - LRAC-11006 | master

### PR DESCRIPTION
**Pull request by ViniLopes20**
https://issues.liferay.com/browse/LRAC-11006

These are other tests that are failing because of this [PR](https://github.com/liferay/com-liferay-osb-asah-private/pull/3557), I found these cases doing the analysis and verified that these cases are passing in the release routine and failing in the master.

### CODE REVIEW

**Comment by ViniLopes20** [comment]
ci:test:sf

**Comment by ViniLopes20** [comment]
ci:test:sf

**Comment by ViniLopes20** [comment]
ci:test:sf

**Review by joshitagaki — APPROVED** [review]
LGTM!

**Review by manuferreira — APPROVED** [review]
LGTM! Thanks, Vini :oncoming_police_car:

**Review by calvinctvo — APPROVED** [review]
Thank you @ViniLopes20 for catching these tests, LGTM

**Comment by ViniLopes20** [comment]
Hi team, Thanks for reviewing!

I'm forwarding it!

**Comment by ViniLopes20** [comment]
ci:forward

**Pull request closed without merging**
