### PR TITLE
Add a test to quarantine - LRAC-10771 | master

### PR DESCRIPTION
**Pull request by ViniLopes20**

### CODE REVIEW

**Comment by ViniLopes20** [comment]
ci:test:sf

**Review by joshitagaki — APPROVED** [review]
LGTM! Yea seems like CSV needs to take some time

**Comment by christianstokes** [comment]
Code looks good. However, in the past, CSV would upload pretty quickly. Do we have an estimate on how long it is taking now? @joshitagaki @ViniLopes20

**Review by manuferreira — APPROVED** [review]
Looks good, Vini. We should investigate more about this CSV issue :cry:

**Comment by joshitagaki** [comment]
> Code looks good. However, in the past, CSV would upload pretty quickly. Do we have an estimate on how long it is taking now? @joshitagaki @ViniLopes20

@christianstokes It took ~5 minutes before I started seeing the csv file changes to individuals

**Comment by ViniLopes20** [comment]
> Code looks good. However, in the past, CSV would upload pretty quickly. Do we have an estimate on how long it is taking now? @joshitagaki @ViniLopes20

Yes @christianstokes and @joshitagaki, our test refreshes the page 50 times waiting for the information to be updated by the CSV and even then it's not sufficient, I think if we increase the number the test could pass, but I don't know if it would be a good solution. What do you think?

**Comment by joshitagaki** [comment]
@ViniLopes20 Yea I agree. I think 50 is already quite a lot of refreshing so I don't think increasing that amount would do much good.

**Review by r4ddek — APPROVED** [review]

**Comment by ViniLopes20** [comment]
Hi team, Thanks for reviewing!

I'm forwarding it!

**Pull request closed without merging**
