### PR TITLE
LPS-126892

### PR DESCRIPTION
**Pull request by alexcandidos**

### CODE REVIEW

**Comment by alexcandidos** [comment]
Pushed to liferay-qa: https://github.com/liferay-qa/liferay-portal/pull/90

**Comment by austinchiang** [comment]
**Reviewing...** :hourglass_flowing_sand: :sunglasses: :headphones:

**Comment by austinchiang** [comment]
Hey @victortrajano try to run SF before you add any commits. That way you don't need to produce any SF commits and can have a cleaner submission :) Thanks!

**Comment by austinchiang** [comment]
See https://github.com/liferay-lima/liferay-portal/pull/1435

**Pull request closed without merging**
