### PR TITLE
AC Test Fix - LRAC-10963 | master

### PR DESCRIPTION
**Pull request by manuferreira**
https://testray.liferay.com/home/-/testray/case_results?testrayBuildId=1704564315&testrayRunId=1704564426 (testray run)
https://issues.liferay.com/browse/LRAC-10963 (ticket)
Hello, this test is a flaky one, but apparently, after some iterations the test works, 15 it's the magic number in that case (but for the most runs the test doesn't even enter in the loop). :grin:

### CODE REVIEW

**Comment by manuferreira** [comment]
ci:test:sf

**Review by ViniLopes20 — APPROVED** [review]
LGTM, unfortunately, the updated information does not appear quickly in the AC, but as you said, it needs to be repeated a few times. Thanks.

**Review by christianstokes — APPROVED** [review]
Looks good, approved!

**Comment by christianstokes** [comment]
ci:forward

**Pull request closed without merging**
