### PR TITLE
AC Automated Test - LRAC-9055 | master

### PR DESCRIPTION
**Pull request by DebSouza**
https://issues.liferay.com/browse/LRAC-9055

### CODE REVIEW

**Comment by DebSouza** [comment]
ci:test:sf

**Comment by joshitagaki** [comment]
This looks good to me! Thanks @DebSouza!
cc: @alexcandidos

**Review by alexcandidos — COMMENTED** [review]
Hi @DebSouza , Thanks for working on it!

The code looks good to me!

I'm forwarding it.

**Comment by alexcandidos** [comment]
ci:foward

**Comment by alexcandidos** [comment]
ci:forward

**Pull request closed without merging**
