### PR TITLE
AC Test Fix - LRAC-10766 | master

### PR DESCRIPTION
**Pull request by ViniLopes20**
https://issues.liferay.com/browse/LRAC-10766

Hey guys, I'm not running PR on CI because of the problem to build it

### CODE REVIEW

**Comment by ViniLopes20** [comment]
ci:test:sf

**Comment by joshitagaki** [comment]
That's weird. I remember we fixed this problem before, but I guess the given individual details changed back?

**Review by r4ddek — APPROVED** [review]

**Review by manuferreira — APPROVED** [review]

**Comment by ViniLopes20** [comment]
Yes @joshitagaki, I remember you sent a PR making these changes, I think it was changed again :(

**Comment by ViniLopes20** [comment]
ci:forward

**Comment by ViniLopes20** [comment]
ci:forward

**Pull request closed without merging**
