### PR TITLE
AC Automated Test - LRAC-9063, LRAC-9064,LRAC-9065, LRAC-9066 | master

### PR DESCRIPTION
**Pull request by rafaellajordao**
https://issues.liferay.com/browse/LRAC-9063
https://issues.liferay.com/browse/LRAC-9064
https://issues.liferay.com/browse/LRAC-9065
https://issues.liferay.com/browse/LRAC-9066

### CODE REVIEW

**Comment by rafaellajordao** [comment]
ci:test:sf

**Comment by christianstokes** [comment]
looks good! cc @alexcandidos

**Comment by alexcandidos** [comment]
hi @christianstokes , thanks for the help reviewing!

Hi @rafaellajordao , Thanks for working on it!

The code looks good to me!

I'm forwarding it.

**Comment by alexcandidos** [comment]
ci:forward

**Pull request closed without merging**
