### PR TITLE
LRAC-8451 | master

### PR DESCRIPTION
**Pull request by Tim-Cao**
https://issues.liferay.com/browse/LRAC-8451

This is only for master.

@alexcandidos

### CODE REVIEW

**Comment by Tim-Cao** [comment]
ci:test:sf

**Comment by Tim-Cao** [comment]
ci:test:sf

**Comment by christianstokes** [comment]
@alexcandidos steps look good, but I am not sure how geolocation will work on CI.  We will just need to keep an eye on the test results.

**Comment by Tim-Cao** [comment]
> @alexcandidos steps look good, but I am not sure how geolocation will work on CI. We will just need to keep an eye on the test results.

Hi @alexcandidos and @christianstokes , the mouse move logic is to trigger geomap fill color shown in html. This behavior could be reproduced manually. It could move over most location.
See https://github.com/liferay-qa/liferay-portal/pull/689/commits/b3922f6c1fa61485d2c29c2da4a8d86dbca4c126

**Comment by alexcandidos** [comment]
Yeah @christianstokes I agree. 

Hey @Tim-Cao , the way how do you implemented seems okay, but I believe we would like to validate the location/country from where we are having the DXP access, not only if the map is being colored or if there is 1 - 100%. I don't know if we have a way to simulate/fake the geolocation on Poshi or even on the Portal, so we could simulate access from any country and validate that Country on the Sessions By Location card. I asked one of the interns to ask on the poshi channel about it https://liferay.slack.com/archives/CD7939WBE/p1629317428062200 . 🤔

**Comment by alexcandidos** [comment]
I think that Locations tests should be also added to the quarantine list based on this limitation, what do you think @christianstokes ?

**Comment by Tim-Cao** [comment]
> Yeah @christianstokes I agree.
> 
> Hey @Tim-Cao , the way how do you implemented seems okay, but I believe we would like to validate the location/country from where we are having the DXP access, not only if the map is being colored or if there is 1 - 100%. I don't know if we have a way to simulate/fake the geolocation on Poshi or even on the Portal, so we could simulate access from any country and validate that Country on the Sessions By Location card. I asked one of the interns to ask on the poshi channel about it https://liferay.slack.com/archives/CD7939WBE/p1629317428062200 . 🤔

Ah. Another challenge.

**Comment by Tim-Cao** [comment]
> I think that Locations tests should be also added to the quarantine list based on this limitation, what do you think @christianstokes ?

Let me try to learn geolocation api on Chrome today

**Comment by Tim-Cao** [comment]
ci:test:sf

**Comment by Tim-Cao** [comment]
> > Yeah @christianstokes I agree.
> > Hey @Tim-Cao , the way how do you implemented seems okay, but I believe we would like to validate the location/country from where we are having the DXP access, not only if the map is being colored or if there is 1 - 100%. I don't know if we have a way to simulate/fake the geolocation on Poshi or even on the Portal, so we could simulate access from any country and validate that Country on the Sessions By Location card. I asked one of the interns to ask on the poshi channel about it https://liferay.slack.com/archives/CD7939WBE/p1629317428062200 . 🤔
> 
> Omg. Another challenge.

Hi @alexcandidos , I've resolved checking country info in my case.

**Comment by Tim-Cao** [comment]
ci:test:sf

**Comment by Tim-Cao** [comment]
ci:forward

**Pull request closed without merging**
