### PR TITLE
AC Test Fix - LRAC-9298 | master

### PR DESCRIPTION
**Pull request by 91nilo**
https://issues.liferay.com/browse/LRAC-9298

### CODE REVIEW

**Comment by 91nilo** [comment]
ci:test:sf

**Comment by 91nilo** [comment]
Fixed tests: 
DataSourcesList#DataSourceListShowsAllDataSources
UserManagement#OwnerCanAddDataSources
UserManagement#AdminCanAddDataSources

**Comment by alexcandidos** [comment]
hi @91nilo, I was not able to see the report at your own PR 91nilo#3 . You need to scope that PR to only run the cases you are investigating.

Could you double-check?

**Comment by alexcandidos** [comment]
hi @91nilo this PR contains a commit to scope the cases to be executed on the CI, please remove it and resend. Thank you! :)

**Pull request closed without merging**
