### PR TITLE
AC Test Fix - LRAC-10834 | master

### PR DESCRIPTION
**Pull request by joshitagaki**
https://issues.liferay.com/browse/LRAC-10834

### CODE REVIEW

**Comment by joshitagaki** [comment]
ci:test:sf

**Comment by ViniLopes20** [comment]
Hey @joshitagaki, Is it not necessary in `SegmentsOverviewAttributeBreakdown#SegmentOverviewDistributionFilteredByBoolean` to remove the breakdown?

**Review by ViniLopes20 — CHANGES_REQUESTED** [review]
Hey @joshitagaki, I think that we could add these tests to quarantine because these continue to fail with CSV. What do you think?

**Comment by joshitagaki** [comment]
> Hey @joshitagaki, Is it not necessary in `SegmentsOverviewAttributeBreakdown#SegmentOverviewDistributionFilteredByBoolean` to remove the breakdown?

It shouldn't be necessary since we're creating a new segment each run so the breakdown should not be there.

**Comment by joshitagaki** [comment]
> Hey @joshitagaki, I think that we could add these tests to quarantine because these continue to fail with CSV. What do you think?

Yea I was thinking about that as well. Looking at the recent runs though it passes a good amount. I can probably add them to this PR though

**Comment by joshitagaki** [comment]
Bad rebase resending in new PR

**Pull request closed without merging**
