### PR TITLE
Revert AC PR - LRAC-11108 | master

### PR DESCRIPTION
**Pull request by ViniLopes20**
https://issues.liferay.com/browse/LRAC-11108 (Bug)

Hey team, I was doing the analysis today and I observed that this case that we made the fix in this [PR](https://github.com/liferay-qa/liferay-portal/pull/1831/files) actually this case didn't need a test fix, it was a [bug](https://issues.liferay.com/browse/LRAC-11108) because this test is a case where **the user has a property, but don't have any data source created**, so the test's empty state was correct before and because of the bug it was the same empty state as when **the user has a property and a data source.** So It is necessary to revert the [PR](https://github.com/liferay-qa/liferay-portal/pull/1831/files) and wait for the bug fix for the test to return to passed.

### CODE REVIEW

**Comment by ViniLopes20** [comment]
ci:test:sf

**Review by joshitagaki — APPROVED** [review]
Thanks Vini! LGTM

**Review by calvinctvo — APPROVED** [review]
Thank you @ViniLopes20 for pointing that out! LGTM

**Review by manuferreira — APPROVED** [review]
LGTM! Thanks Vini :police_officer:

**Comment by ViniLopes20** [comment]
Hi team, Thanks for reviewing!

I'm forwarding it!

**Comment by ViniLopes20** [comment]
ci:forward

**Pull request closed without merging**
