### PR TITLE
AC Test Fix - LRAC-10019 | master 

### PR DESCRIPTION
**Pull request by manuferreira**
https://github.com/manuferreira/liferay-portal/pull/18
https://issues.liferay.com/browse/LRAC-10019

### CODE REVIEW

**Comment by manuferreira** [comment]
ci:test:sf

**Comment by manuferreira** [comment]
ci:test:sf

**Comment by manuferreira** [comment]
ci:test:sf

**Comment by alexcandidos** [comment]
Hi @manuferreira , Thanks for working on it!

The code looks good to me!

I'm forwarding it.

**Comment by alexcandidos** [comment]
ci:forward

**Review by AfonsoHSantos — APPROVED** [review]

**Pull request closed without merging**
