### PR TITLE
 AC Test Fix - LRAC-9426 | master

### PR DESCRIPTION
**Pull request by 91nilo**
https://issues.liferay.com/browse/LRAC-9426
Run: https://testray.liferay.com/home/-/testray/runs?testrayBuildId=1564565648

### CODE REVIEW

**Comment by 91nilo** [comment]
ci:test:sf

**Comment by 91nilo** [comment]
ci:test:sf

**Comment by 91nilo** [comment]
Done. Thank you @ViniLopes20

**Comment by christianstokes** [comment]
ci:forward

**Pull request closed without merging**
