### PR TITLE
Ac Automated Test - LRAC-8356, LRAC-8357, LRAC-8358, LRAC-8394, LRAC-8395 | master

### PR DESCRIPTION
**Pull request by 91nilo**
https://issues.liferay.com/browse/LRAC-8356
https://issues.liferay.com/browse/LRAC-8874 (Refactor)
https://issues.liferay.com/browse/LRAC-8357
https://issues.liferay.com/browse/LRAC-8875 (Refactor)
https://issues.liferay.com/browse/LRAC-8358
https://issues.liferay.com/browse/LRAC-8878 (Refactor)
https://issues.liferay.com/browse/LRAC-8394
https://issues.liferay.com/browse/LRAC-8876 (Refactor)
https://issues.liferay.com/browse/LRAC-8395
https://issues.liferay.com/browse/LRAC-8877 (Refactor)

### CODE REVIEW

**Comment by 91nilo** [comment]
Code from https://github.com/liferay-qa/liferay-portal/pull/620.
Just divided in 1 commit per testcase, added the quarantine label and comments.

**Comment by 91nilo** [comment]
ci:test:sf

**Comment by 91nilo** [comment]
Updated the new refactor tickets number on the tests.

**Comment by 91nilo** [comment]
ci:test:sf

**Comment by alexcandidos** [comment]
Hi @91nilo , Thanks for working on it!

The code looks good to me!

I'm forwarding it.

**Comment by alexcandidos** [comment]
ci:forward

**Pull request closed without merging**
