### PR TITLE
LRAC-9180, LRAC-9182, LRAC-9183 | master

### PR DESCRIPTION
**Pull request by Tim-Cao**
https://issues.liferay.com/browse/LRAC-9180
https://issues.liferay.com/browse/LRAC-9182
https://issues.liferay.com/browse/LRAC-9183

This is only for master.

@alexcandidos

### CODE REVIEW

**Comment by Tim-Cao** [comment]
ci:test:sf

**Comment by Tim-Cao** [comment]
ci:test:sf

**Comment by Tim-Cao** [comment]
ci:test:sf

**Comment by Tim-Cao** [comment]
ci:test:sf

**Comment by christianstokes** [comment]
@Tim-Cao looks good to me!

cc @alexcandidos

**Comment by alexcandidos** [comment]
hi @christianstokes  , thanks for helping to review it.

Hi @Tim-Cao , Thanks for working on it!

The code looks good to me!

Could you please just fix the conflict, then we can proceed to forward it?

**Comment by alexcandidos** [comment]
hi @Tim-Cao , I believe these two test cases were already sent through https://github.com/liferay-qa/liferay-portal/pull/953, right? So maybe you can just close this PR. Could you please confirm? Thanks!

**Comment by Tim-Cao** [comment]
Hi @alexcandidos, you’re right. Closed this PR. Thanks.

**Comment by Tim-Cao** [comment]
ci:close

**Pull request closed without merging**
