### PR TITLE
Remove testcase - LRAC-11051 | master

### PR DESCRIPTION
**Pull request by joshitagaki**
https://issues.liferay.com/browse/LRAC-11051
This testcase is covered by KnownIndividualsSearch#SearchIndividualDetails

### CODE REVIEW

**Comment by joshitagaki** [comment]
ci:test:sf

**Review by calvinctvo — APPROVED** [review]
LGTM thank you Josh

**Review by ViniLopes20 — APPROVED** [review]
Nice catch. LGTM!

**Review by manuferreira — APPROVED** [review]
LGTM! thanks Josh

**Comment by ViniLopes20** [comment]
ci:forward

**Pull request closed without merging**
