### PR TITLE
LRAC-9022,LRAC-9024,LRAC-9026,LRAC-9028,LRAC-9029,LRAC-9030,LRAC-9031,LRAC-9032,LRAC-9033 | Master

### PR DESCRIPTION
**Pull request by Hanlf**
https://issues.liferay.com/browse/LRAC-9022
https://issues.liferay.com/browse/LRAC-9024
https://issues.liferay.com/browse/LRAC-9026
https://issues.liferay.com/browse/LRAC-9028
https://issues.liferay.com/browse/LRAC-9029
https://issues.liferay.com/browse/LRAC-9030
https://issues.liferay.com/browse/LRAC-9031
https://issues.liferay.com/browse/LRAC-9032
https://issues.liferay.com/browse/LRAC-9033

### CODE REVIEW

**Comment by Hanlf** [comment]
ci:test:sf

**Comment by christianstokes** [comment]
These tests look really good, only a few changes!

Thank you @Hanlf 

cc @alexcandidos

**Comment by Hanlf** [comment]
ci:test:sf

**Comment by Hanlf** [comment]
Hi @christianstokes the test has been updated, please review.

**Comment by alexcandidos** [comment]
hi @christianstokes  , thanks for helping to review it.

Hi @Hanlf , Thanks for working on it!

The code looks good to me!

I'm forwarding it.

**Comment by alexcandidos** [comment]
ci:forward

**Pull request closed without merging**
