### PR TITLE
AC Automated Test - LRAC-8439 LRAC-8453 LRAC-8454 | master

### PR DESCRIPTION
**Pull request by kenduenwald**
https://issues.liferay.com/browse/LRAC-8439
https://issues.liferay.com/browse/LRAC-8453
https://issues.liferay.com/browse/LRAC-8454

### CODE REVIEW

**Comment by kenduenwald** [comment]
ci:test:sf

**Comment by kenduenwald** [comment]
ci:test:sf

**Comment by kenduenwald** [comment]
ci:test:sf

**Comment by alexcandidos** [comment]
Hi @kenduenwald , Thanks for working on it!

The code looks good to me! Could you please just solve the conflict and push it again? Thanks!

**Comment by kenduenwald** [comment]
@alexcandidos, branch has been rebased on top of current upstream and conflicts have been resolved.

**Comment by kenduenwald** [comment]
ci:test:sf

**Comment by alexcandidos** [comment]
Hi @kenduenwald , Thanks for working on it!

The code looks good to me!

I'm forwarding it.

**Comment by alexcandidos** [comment]
ci:forward

**Pull request closed without merging**
