### PR TITLE
AC Test Fix - LRAC-9615 | master

### PR DESCRIPTION
**Pull request by ViniLopes20**
https://issues.liferay.com/browse/LRAC-9615

### CODE REVIEW

**Comment by ViniLopes20** [comment]
ci:test:sf

**Comment by ViniLopes20** [comment]
This PR resolved the ticket issue, but the test is still failing at another step.

**Comment by alexcandidos** [comment]
@joshitagaki this is the code we were discussing ;)

Hi @ViniLopes20 , Thanks for working on it!

The code looks good to me!

I'm forwarding it.

**Comment by alexcandidos** [comment]
ci:forward

**Pull request closed without merging**
