### PR TITLE
AC Test Fix - LRAC-9615 | master

### PR DESCRIPTION
**Pull request by joshitagaki**
https://issues.liferay.com/browse/LRAC-9615
https://github.com/joshitagaki/liferay-portal/pull/27

### CODE REVIEW

**Comment by joshitagaki** [comment]
ci:test:sf

**Comment by joshitagaki** [comment]
Trying to test the build here: https://github.com/joshitagaki/liferay-portal/pull/27. Continues to fail earlier in the test than where the changes occurs.

**Comment by alexcandidos** [comment]
hi @joshitagaki, Thanks for working on it! Yesterday (@ViniLopes20 @manuferreira and @AfonsoHSantos ) were analyzing this test Yesterday. I think Vini added a new macro `isLessThan` at `TestUtils` where we were validating the max load time (like if we were doing a performance testing, where we were checking if the page load was less than 1500ms instead of lower expected time since if the page is loading fast it is not a problem, but the opposite would be, considering a simple DXP page as in this case).

hey @ViniLopes20 , when possible, submit that commit so @joshitagaki can look better and select the best approach.

**Comment by joshitagaki** [comment]
@alexcandidos Thanks! @ViniLopes20 Did you run into an issue when testing on CI where the test would start failing on an earlier step before reaching the isLessThan macro? From my runs it was failing on `task ("View the tabBlurred event triggered")` where the changes shouldn't affect it.

**Comment by ViniLopes20** [comment]
Yes @joshitagaki, the macro is failing some of our tests, yesterday we were investigating the possible cause of this failure, but for the macro `ACUtils.assertRequestCommonPropertiesValue`, but I believe the fault must be the same in the `ACUtils.assertEventPresent`. We are thinking that the problem may be the query that is used or the `ProxyUtil.getHarRecording` is not returning as expected. We still haven't found a solution

**Comment by joshitagaki** [comment]
Closing ticket in favor of changes provided by @ViniLopes20

**Pull request closed without merging**
