### PR TITLE
AC Test Fix - LRAC-9454 | master

### PR DESCRIPTION
**Pull request by manuferreira**
https://testray.liferay.com/home/-/testray/subtasks/1565354342 (Testray)
https://issues.liferay.com/browse/LRAC-9454 (Fix ticket)
https://github.com/manuferreira/liferay-portal/pull/9

### CODE REVIEW

**Comment by manuferreira** [comment]
ci:test:sf

**Comment by joshitagaki** [comment]
Hi @manuferreira, for this test fix the date format should also be checking "MMM d - d" as well. So may need to add something like if "MMM d - d" or "MMM d - MMM d" is not present then the test will fail. If you need any help with this let me know. Thanks for working on it!

**Comment by manuferreira** [comment]
Hi @joshitagaki, yes you are right. I will work on this right now :)

**Comment by manuferreira** [comment]
ci:test:sf

**Comment by christianstokes** [comment]
ci:forward

**Pull request closed without merging**
