### PR TITLE
AC Automated Test - LRAC-8585 | master

### PR DESCRIPTION
**Pull request by mateusralv**
https://issues.liferay.com/browse/LRAC-8585

### CODE REVIEW

**Comment by mateusralv** [comment]
https://issues.liferay.com/browse/LRAC-8585

**Comment by ViniLopes20** [comment]
ci:test:sf

**Review by alexcandidos — COMMENTED** [review]
Hi @mateusralv , Thanks for working on it!

The code looks good to me!

I'm forwarding it.

**Comment by alexcandidos** [comment]
ci:forward

**Comment by ViniLopes20** [comment]
ci:reopen

**Comment by ViniLopes20** [comment]
ci:reopen

**Pull request closed without merging**
