### PR TITLE
AC Test Fix - LRAC-10772 | master

### PR DESCRIPTION
**Pull request by manuferreira**
https://issues.liferay.com/browse/LRAC-10772 (ticket)
Hey, I didn't run the PR because CI is having problems.

### CODE REVIEW

**Comment by manuferreira** [comment]
ci:test:sf

**Comment by r4ddek** [comment]
Looks good, thanks @manuferreira

**Review by r4ddek — APPROVED** [review]

**Review by christianstokes — APPROVED** [review]
Looks good.

**Comment by christianstokes** [comment]
ci:foward

**Comment by christianstokes** [comment]
ci:forward

**Pull request closed without merging**
