### PR TITLE
AC Automated Test - LRAC-8628 | master

### PR DESCRIPTION
**Pull request by epark18**
https://issues.liferay.com/browse/LRAC-8628

### CODE REVIEW

**Comment by epark18** [comment]
Tried to make this test resemble [this test](https://github.com/liferay/com-liferay-osb-faro-private/blob/7.1.x/osb-faro-functional-test/src/testIntegration/resources/features/segments/profile/AssertSegmentDistributionTextProperty.feature). Will make necessary adjustments. Thank you!

**Comment by christianstokes** [comment]
Looks great!

cc @alexcandidos

**Comment by alexcandidos** [comment]
hi @christianstokes , thanks for the help reviewing!

Hi @epark18 , Thanks for working on it!

The code looks good to me!

I'm forwarding it.

**Comment by alexcandidos** [comment]
ci:forward

**Pull request closed without merging**
