### PR TITLE
AC Test Fix - LRAC-11035 | master

### PR DESCRIPTION
**Pull request by manuferreira**
https://testray.liferay.com/home/-/testray/case_results?testrayBuildId=1740242514&testrayRunId=1740409960 (testray run)
https://issues.liferay.com/browse/LRAC-11035 (ticket)

### CODE REVIEW

**Comment by manuferreira** [comment]
ci:test:sf

**Review by ViniLopes20 — APPROVED** [review]
LGTM

**Review by joshitagaki — APPROVED** [review]
LGTM!

**Review by christianstokes — APPROVED** [review]
Approved

**Comment by christianstokes** [comment]
ci:forward

**Pull request closed without merging**
