### PR TITLE
AC Test Fix - LRAC-9631 | master

### PR DESCRIPTION
**Pull request by joshitagaki**
https://issues.liferay.com/browse/LRAC-9631
https://github.com/joshitagaki/liferay-portal/pull/24

### CODE REVIEW

**Comment by joshitagaki** [comment]
ci:test:sf

**Comment by joshitagaki** [comment]
ci:test:sf

**Comment by alexcandidos** [comment]
Hi @joshitagaki , Thanks for working on it!

The code looks good to me!

I'm forwarding it.

**Comment by alexcandidos** [comment]
ci:forward

**Pull request closed without merging**
