### PR TITLE
Remove from Quarantine AC Test - LRAC-8176

### PR DESCRIPTION
**Pull request by ViniLopes20**
1. [Testray](https://testray.liferay.com/home/-/testray/case_results/1634782254/history?tab=result&hideFilterPin=true)
2. [Testray](https://testray.liferay.com/home/-/testray/case_results/1634782093/history?tab=result&hideFilterPin=true)
3. [Testray](https://testray.liferay.com/home/-/testray/case_results/1634781990/history?tab=result&hideFilterPin=true)
4. [Testray](https://testray.liferay.com/home/-/testray/case_results/1634781896/history?tab=result&hideFilterPin=true)
5. [Testray](https://testray.liferay.com/home/-/testray/case_results/1634781670/history?tab=result&hideFilterPin=true)
6. [Testray](https://testray.liferay.com/home/-/testray/case_results/1634781927/history?tab=result&hideFilterPin=true)
7. [Testray](https://testray.liferay.com/home/-/testray/case_results/1634781869/history?tab=result&hideFilterPin=true)
8. [Testray](https://testray.liferay.com/home/-/testray/case_results/1634781802/history?tab=result&hideFilterPin=true)
9. [Testray](https://testray.liferay.com/home/-/testray/case_results/1634782057/history?tab=result&hideFilterPin=true)
10. [Testray](https://testray.liferay.com/home/-/testray/case_results/1634782214/history?tab=result&hideFilterPin=true)
11. [Testray](https://testray.liferay.com/home/-/testray/case_results/1634782118/history?tab=result&hideFilterPin=true)
12. [Testray](https://testray.liferay.com/home/-/testray/case_results/1634782086/history?tab=result&hideFilterPin=true)
13. [Testray](https://testray.liferay.com/home/-/testray/case_results/1634782085/history?tab=result&hideFilterPin=true)
14. [Testray](https://testray.liferay.com/home/-/testray/case_results/1634782026/history?tab=result&hideFilterPin=true)
15. [Testray](https://testray.liferay.com/home/-/testray/case_results/1634781754/history?tab=result&hideFilterPin=true)
16. [Testray](https://testray.liferay.com/home/-/testray/case_results/1634782125/history?tab=result&hideFilterPin=true)
17. [Testray](https://testray.liferay.com/home/-/testray/case_results/1634782068/history?tab=result&hideFilterPin=true)
18. [Testray](https://testray.liferay.com/home/-/testray/case_results/1634782061/history?tab=result&hideFilterPin=true)
19. [Testray](https://testray.liferay.com/home/-/testray/case_results/1634782170/history?tab=result&hideFilterPin=true)
20. [Testray](https://testray.liferay.com/home/-/testray/case_results/1634782094/history?tab=result&hideFilterPin=true)
21. [Testray](https://testray.liferay.com/home/-/testray/case_results/1634782210/history?tab=result&hideFilterPin=true)
22. [Testray](https://testray.liferay.com/home/-/testray/case_results/1634782161/history?tab=result&hideFilterPin=true)
23. [Testray](https://testray.liferay.com/home/-/testray/case_results/1634782088/history?tab=result&hideFilterPin=true)
24. [Testray](https://testray.liferay.com/home/-/testray/case_results/1634782043/history?tab=result&hideFilterPin=true)
25. [Testray](https://testray.liferay.com/home/-/testray/case_results/1634781847/history?tab=result&hideFilterPin=true)
26. [Testray](https://testray.liferay.com/home/-/testray/case_results/1634781809/history?tab=result&hideFilterPin=true)
27. [Testray](https://testray.liferay.com/home/-/testray/case_results/1634781773/history?tab=result&hideFilterPin=true)
28. [Testray](https://testray.liferay.com/home/-/testray/case_results/1634781726/history?tab=result&hideFilterPin=true)
29. [Testray](https://testray.liferay.com/home/-/testray/case_results/1634781734/history?tab=result&hideFilterPin=true)

### CODE REVIEW

**Comment by ViniLopes20** [comment]
ci:test:sf

**Review by joshitagaki — APPROVED** [review]
Thanks for looking into these tests! Looks good to me

**Comment by christianstokes** [comment]
It looks great Vini, let's go for it.

**Review by christianstokes — APPROVED** [review]

**Review by manuferreira — APPROVED** [review]

**Comment by ViniLopes20** [comment]
ci:forward

**Pull request closed without merging**
