### PR TITLE
AC Automated Test LRAC-8603 | master

### PR DESCRIPTION
**Pull request by 91nilo**
https://issues.liferay.com/browse/LRAC-8500
https://issues.liferay.com/browse/LRAC-9167 (Refactor)

https://issues.liferay.com/browse/LRAC-8501 
https://issues.liferay.com/browse/LRAC-9168 (Refactor)

https://issues.liferay.com/browse/LRAC-8502
https://issues.liferay.com/browse/LRAC-9169 (Refactor)

https://issues.liferay.com/browse/LRAC-8619
https://issues.liferay.com/browse/LRAC-9170 (Refactor)

https://issues.liferay.com/browse/LRAC-8620
https://issues.liferay.com/browse/LRAC-9171 (Refactor)

https://issues.liferay.com/browse/LRAC-8621
https://issues.liferay.com/browse/LRAC-9172 (Refactor)

https://issues.liferay.com/browse/LRAC-8604
https://issues.liferay.com/browse/LRAC-9155 (Refactor)

https://issues.liferay.com/browse/LRAC-8605
https://issues.liferay.com/browse/LRAC-9156 (Refactor)

https://issues.liferay.com/browse/LRAC-8606
https://issues.liferay.com/browse/LRAC-9157 (Refactor)

https://issues.liferay.com/browse/LRAC-8607
https://issues.liferay.com/browse/LRAC-9158 (Refactor)

https://issues.liferay.com/browse/LRAC-8608
https://issues.liferay.com/browse/LRAC-9159 (Refactor)

https://issues.liferay.com/browse/LRAC-8609
https://issues.liferay.com/browse/LRAC-9160 (Refactor)

https://issues.liferay.com/browse/LRAC-8610
https://issues.liferay.com/browse/LRAC-9161 (Refactor)

https://issues.liferay.com/browse/LRAC-8611
https://issues.liferay.com/browse/LRAC-9162 (Refactor)

https://issues.liferay.com/browse/LRAC-8612
https://issues.liferay.com/browse/LRAC-9163 (Refactor)

https://issues.liferay.com/browse/LRAC-8613
https://issues.liferay.com/browse/LRAC-9164 (Refactor)

https://issues.liferay.com/browse/LRAC-8614
https://issues.liferay.com/browse/LRAC-9165 (Refactor)

https://issues.liferay.com/browse/LRAC-8616
https://issues.liferay.com/browse/LRAC-9166 (Refactor)

### CODE REVIEW

**Comment by 91nilo** [comment]
ci:test:sf

**Comment by 91nilo** [comment]
ci:test:sf

**Comment by alexcandidos** [comment]
Hi @91nilo , Thanks for working on it!

I'm forwarding it.

**Comment by alexcandidos** [comment]
ci:forward

**Pull request closed without merging**
