### PR TITLE
AC Test Fix - LRAC-10891 | master

### PR DESCRIPTION
**Pull request by manuferreira**
https://testray.liferay.com/home/-/testray/case_results?testrayBuildId=1658040834&testrayRunId=1658044449 (testray run)
https://issues.liferay.com/browse/LRAC-10891 (ticket)

### CODE REVIEW

**Comment by manuferreira** [comment]
ci:test:sf

**Review by joshitagaki — APPROVED** [review]
Nice LGTM! Hopefully we can use that new parameter on some other tests

**Comment by manuferreira** [comment]
ci:test:sf

**Review by ViniLopes20 — APPROVED** [review]
LGTM, congratulations!! 😄

**Review by joshitagaki — APPROVED** [review]

**Comment by christianstokes** [comment]
ci:forward

**Pull request closed without merging**
