### PR TITLE
master-lrac-8441

### PR DESCRIPTION
**Pull request by suilin**
https://issues.liferay.com/browse/LRAC-8441

### CODE REVIEW

**Comment by suilin** [comment]
ci:test:sf

**Comment by ViniLopes20** [comment]
LGTM!

**Comment by alexcandidos** [comment]
Hi @suilin , Thanks for working on it!

The code looks good to me!

Could you please just rebase to fix the conflict and then just proceed with ci forward?

Thanks!

**Comment by suilin** [comment]
ci:forward

**Pull request closed without merging**
