### PR TITLE
AC Test Active - LRAC-9626 | master

### PR DESCRIPTION
**Pull request by ViniLopes20**
https://issues.liferay.com/browse/LRAC-9626
https://issues.liferay.com/browse/LRAC-8774
https://issues.liferay.com/browse/LRAC-9400
https://issues.liferay.com/browse/LRAC-9671

quarantine tickets:
https://issues.liferay.com/browse/LRAC-9805
https://issues.liferay.com/browse/LRAC-9806
https://issues.liferay.com/browse/LRAC-9807
https://issues.liferay.com/browse/LRAC-9808

### CODE REVIEW

**Comment by ViniLopes20** [comment]
ci:test:sf

**Comment by ViniLopes20** [comment]
ci:test:sf

**Comment by ViniLopes20** [comment]
ci:test:sf

**Comment by alexcandidos** [comment]
Hi @ViniLopes20 , Thanks for working on it!

The code looks good to me!

I'm forwarding it.

**Comment by alexcandidos** [comment]
ci:forward

**Pull request closed without merging**
