### PR TITLE
AC Automated Test - LRAC-9273 | master

### PR DESCRIPTION
**Pull request by andreefarias**
https://issues.liferay.com/browse/LRAC-9273

https://github.com/liferay-qa/liferay-portal/pull/1012 (Update)

### CODE REVIEW

**Comment by andreefarias** [comment]
ci:test:sf

**Comment by andreefarias** [comment]
ci:test:sf

**Comment by alexcandidos** [comment]
Hi @andreefarias , Thanks for working on it!

The code looks good to me!

I'm forwarding it.

**Comment by alexcandidos** [comment]
ci:forward

**Pull request closed without merging**
