### PR TITLE
AC Automated Test - LRAC-10671 | master

### PR DESCRIPTION
**Pull request by ViniLopes20**
https://issues.liferay.com/browse/LRAC-10671
https://issues.liferay.com/browse/LRAC-10672
https://issues.liferay.com/browse/LRAC-10673
https://issues.liferay.com/browse/LRAC-10494 (bug 1)
https://issues.liferay.com/browse/LRAC-10692 (bug 2)
[Testray](https://testray.liferay.com/home/-/testray/case_results/index?p_p_state=normal&orderByCol=status_sortable&orderByType=asc&testrayBuildId=1649147757)

### CODE REVIEW

**Comment by ViniLopes20** [comment]
ci:test:sf

**Review by manuferreira — APPROVED** [review]
Looks great Vini, thanks.

**Review by joshitagaki — APPROVED** [review]
Nice looks good to me!

**Review by r4ddek — APPROVED** [review]

**Comment by ViniLopes20** [comment]
Hi team, Thanks for reviewing!

I'm forwarding it!

**Comment by ViniLopes20** [comment]
ci:forward

**Pull request closed without merging**
