### PR TITLE
AC Test Fix - LRAC-10710 | master

### PR DESCRIPTION
**Pull request by ViniLopes20**
https://issues.liferay.com/browse/LRAC-10710

Hey guys, I'm not running PR on CI because of the problem to build it

More information about the solution: [Link](https://issues.liferay.com/browse/LRAC-10710?focusedCommentId=2645796&page=com.atlassian.jira.plugin.system.issuetabpanels%3Acomment-tabpanel#comment-2645796)

### CODE REVIEW

**Comment by ViniLopes20** [comment]
ci:test:sf

**Review by manuferreira — APPROVED** [review]
Hey @ViniLopes20 I remember we discussed this problem one day. Looks good, thank you :wink:

**Review by joshitagaki — APPROVED** [review]
Looks good @ViniLopes20

**Review by r4ddek — APPROVED** [review]

**Comment by ViniLopes20** [comment]
Hi team, Thanks for reviewing!

I'm forwarding it!

**Comment by ViniLopes20** [comment]
ci:forward

**Pull request closed without merging**
