### PR TITLE
AC Test fix - LRAC-10599 | master

### PR DESCRIPTION
**Pull request by joshitagaki**
https://issues.liferay.com/browse/LRAC-10599
This is the last batch of empty state tests

### CODE REVIEW

**Comment by joshitagaki** [comment]
ci:test:sf

**Review by ViniLopes20 — APPROVED** [review]
LGTM, thanks @joshitagaki

**Review by calvinctvo — APPROVED** [review]
LGTM! Thank you @joshitagaki

**Review by manuferreira — APPROVED** [review]
LGTM, Thanks Josh! :+1:

**Comment by ViniLopes20** [comment]
Hi team, Thanks for reviewing!

I'm forwarding it!

**Comment by ViniLopes20** [comment]
ci:forward

**Pull request closed without merging**
