### PR TITLE
AC Automated Test LRAC-8603 | master

### PR DESCRIPTION
**Pull request by kenduenwald**
https://issues.liferay.com/browse/LRAC-8603
https://issues.liferay.com/browse/LRAC-8604
https://issues.liferay.com/browse/LRAC-8605
https://issues.liferay.com/browse/LRAC-8606
https://issues.liferay.com/browse/LRAC-8607
https://issues.liferay.com/browse/LRAC-8608
https://issues.liferay.com/browse/LRAC-8609
https://issues.liferay.com/browse/LRAC-8610
https://issues.liferay.com/browse/LRAC-8611
https://issues.liferay.com/browse/LRAC-8612
https://issues.liferay.com/browse/LRAC-8613
https://issues.liferay.com/browse/LRAC-8614
https://issues.liferay.com/browse/LRAC-8616

### CODE REVIEW

**Comment by kenduenwald** [comment]
ci:test:sf

**Comment by kenduenwald** [comment]
ci:test:sf

**Comment by alexcandidos** [comment]
Hi @kenduenwald , Thanks for working on it!

The code looks good to me!

I'm forwarding it.

**Comment by alexcandidos** [comment]
ci:forward

**Pull request closed without merging**
