### PR TITLE
AC Automated Test - LRAC-8585 | master

### PR DESCRIPTION
**Pull request by mateusralv**
https://issues.liferay.com/browse/LRAC-8585

### CODE REVIEW

**Comment by ViniLopes20** [comment]
ci:forward

**Comment by alexcandidos** [comment]
ci:test:sf

**Comment by alexcandidos** [comment]
hi @mateusralv could you please try to rebase and format your code locally to see if these errors are solved?

cc: @ViniLopes20

**Comment by ViniLopes20** [comment]
ci:close

**Pull request closed without merging**
