### PR TITLE
LRAC-9034, LRAC-9037, LRAC-9038 | master

### PR DESCRIPTION
**Pull request by Tim-Cao**
https://issues.liferay.com/browse/LRAC-9034
https://issues.liferay.com/browse/LRAC-9037
https://issues.liferay.com/browse/LRAC-9038

This is only for master.

@alexcandidos

### CODE REVIEW

**Comment by Tim-Cao** [comment]
ci:test:sf

**Comment by joshitagaki** [comment]
Looks good to me! Thanks @Tim-Cao!
cc: @alexcandidos

**Comment by Tim-Cao** [comment]
ci:test:sf

**Comment by alexcandidos** [comment]
Hi @Tim-Cao , Thanks for working on it!

The code looks good to me!

I'm forwarding it.

**Comment by alexcandidos** [comment]
ci:forward

**Pull request closed without merging**
