### PR TITLE
LPS-126387

### PR DESCRIPTION
**Pull request by alexcandidos**

### CODE REVIEW

**Comment by Tim-Cao** [comment]
Hi @alexcandidos, this case is already covered by LocalizedNestedFieldsStructure#CheckLocalizationOfStructureUponLanguageChange

**Comment by emanuelfisilva** [comment]
Thanks for your review @Tim-Cao , but we'll choose to keep these validations separated.

**Comment by Tim-Cao** [comment]
See https://github.com/liferay-echo/liferay-portal/pull/3782
View total diff https://github.com/liferay-echo/liferay-portal/pull/3782/commits/89ffd8e0fad3d4009115cc8902af6b83ae7e80e4

**Comment by Tim-Cao** [comment]
ci:close

**Pull request closed without merging**
