### PR TITLE
LRAC-8514, LRAC-8515, LRAC-8516, LRAC-8517 | master

### PR DESCRIPTION
**Pull request by Tim-Cao**
https://issues.liferay.com/browse/LRAC-8514
https://issues.liferay.com/browse/LRAC-8728 (Refactor ticket)
https://issues.liferay.com/browse/LRAC-8515
https://issues.liferay.com/browse/LRAC-8729 (Refactor ticket)
https://issues.liferay.com/browse/LRAC-8516
https://issues.liferay.com/browse/LRAC-8730 (Refactor ticket)
https://issues.liferay.com/browse/LRAC-8517
https://issues.liferay.com/browse/LRAC-8731 (Refactor ticket)

This is only for master.

@alexcandidos
@christianstokes

### CODE REVIEW

**Comment by Tim-Cao** [comment]
ci:test:nocompile

**Comment by Tim-Cao** [comment]
ci:test

**Comment by Tim-Cao** [comment]
ci:test

**Comment by Tim-Cao** [comment]
ci:test

**Comment by Tim-Cao** [comment]
ci:test

**Comment by Tim-Cao** [comment]
ci:test

**Comment by Tim-Cao** [comment]
ci:test

**Comment by Tim-Cao** [comment]
ci:test

**Comment by Tim-Cao** [comment]
ci:test:sf

**Comment by Tim-Cao** [comment]
ci:test:sf

**Comment by alexcandidos** [comment]
Hi @Tim-Cao , Thanks for working on it!

Thanks for creating the refactor tickets, you did it very well! 🥇 

The code looks good to me!

I'm forwarding it.

**Comment by alexcandidos** [comment]
ci:forward

**Pull request closed without merging**
