### PR TITLE
AC Test Fix - LRAC-9302 | master

### PR DESCRIPTION
**Pull request by mateusralv**
https://github.com/mateusralv/liferay-portal/pull/3
https://issues.liferay.com/browse/LRAC-9302

### CODE REVIEW

**Comment by MathausC** [comment]
ci:test:sf

**Comment by mateusralv** [comment]
ci:test:sf

**Comment by alexcandidos** [comment]
Hi @mateusralv , Thanks for working on it!

The code looks good to me!

I'm forwarding it.

**Comment by alexcandidos** [comment]
ci:forward

**Pull request closed without merging**
