### PR TITLE
AC Automated Test - LRAC-8112 | master

### PR DESCRIPTION
**Pull request by catarineaguiar**
https://issues.liferay.com/browse/LRAC-8112
https://issues.liferay.com/browse/LRAC-8990 Refactor Ticket

### CODE REVIEW

**Comment by ViniLopes20** [comment]
ci:test:sf

**Comment by ViniLopes20** [comment]
ci:test:sf

**Comment by ViniLopes20** [comment]
Hi @catarineaguiar, fix the CI SF failure issue

I'm closing this PR. Please open a new one when the fixes are ready. Thanks!

**Comment by catarineaguiar** [comment]
New PR #864

**Pull request closed without merging**
