### PR TITLE
LPS 126459

### PR DESCRIPTION
**Pull request by alexcandidos**

### CODE REVIEW

**Comment by nikki-pru** [comment]
ci:test:sf

**Comment by nikki-pru** [comment]
ci:test:relevant

**Comment by liuxingye** [comment]
Reviewing...

**Comment by liuxingye** [comment]
Hi @alexcandidos please close this PR and see https://github.com/austinchiang/liferay-portal/pull/935 for more details.

**Comment by alexcandidos** [comment]
Thanks @liuxingye !

**Pull request closed without merging**
