### PR TITLE
AC Test Fix - LRAC-9707 Add container restart macro to prevent users from being immediately unavailable due to lazy cache updates (redis)

### PR DESCRIPTION
**Pull request by r4ddek**
https://issues.liferay.com/browse/LRAC-9707

### CODE REVIEW

**Review by ViniLopes20 — APPROVED** [review]

**Comment by ViniLopes20** [comment]
ci:test:sf

**Review by joshitagaki — APPROVED** [review]
Nice catch @r4ddek. Looks good to me. We'll need to look to try and implement this in some of our flaky tests

**Review by manuferreira — APPROVED** [review]
Thank you Leo!! :heart_decoration:

**Comment by r4ddek** [comment]
> Nice catch @r4ddek. Looks good to me. We'll need to look to try and implement this in some of our flaky tests

Yea, for the individuals issue restarting osbasahredis did it. All that remains now is to come up with a strategy to implement this macro in a subroutine to cover all individual tests or write it one by one (yikes!).

**Review by calvinctvo — APPROVED** [review]
LGTM

**Comment by r4ddek** [comment]
@joshitagaki apparently including it in the close sessions subroutine didn't break anything and the broken tests passed. @ViniLopes20 and I will remove the quarantine flags from a few tests in this batch just to make sure we cover all the tests on the list. TL;DR: there's no need to go through each test implementing the macro hehe 🎉

**Comment by r4ddek** [comment]
Waiting for final replies before merging and closing this PR.

**Comment by ViniLopes20** [comment]
ci:open

**Comment by r4ddek** [comment]
ci:forward

**Pull request merged**
