### PR TITLE
AC Test Infrastructure fix - LRAC-11047 | master

### PR DESCRIPTION
**Pull request by joshitagaki**
https://issues.liferay.com/browse/LRAC-11047

### CODE REVIEW

**Comment by joshitagaki** [comment]
ci:test:sf

**Review by calvinctvo — APPROVED** [review]
Hey @joshitagaki , the code LGTM

**Review by ViniLopes20 — APPROVED** [review]
LGTM

**Comment by christianstokes** [comment]
ci:forward

**Review by christianstokes — APPROVED** [review]
Approved

**Review by manuferreira — APPROVED** [review]

**Pull request closed without merging**
