### PR TITLE
LRAC-8313, LRAC-8312 | master

### PR DESCRIPTION
**Pull request by brookedalton**
https://issues.liferay.com/browse/LRAC-8313
https://issues.liferay.com/browse/LRAC-8745(Refactor)

https://issues.liferay.com/browse/LRAC-8312
https://issues.liferay.com/browse/LRAC-8746(Refactor)

### CODE REVIEW

**Comment by brookedalton** [comment]
ci:test:sf

**Comment by christianstokes** [comment]
Notes for @alexcandidos when reviewing:
Steps looks good. In the future we will need to do something about the big wait/pause, but it will probably be an issue for a lot of tests

**Comment by alexcandidos** [comment]
Yeah @christianstokes , we need to refactor the pauses in the future for our tests.

Hi @brookedalton , Thanks for working on it!

The code looks good to me!

I'm forwarding it.

**Comment by alexcandidos** [comment]
ci:forward

**Pull request closed without merging**
