### PR TITLE
LPS-126302

### PR DESCRIPTION
**Pull request by alexcandidos**

### CODE REVIEW

**Comment by Tim-Cao** [comment]
Hi @alexcandidos, this case is already covered by FieldGroups#DuplicateANestedFieldGroup and FieldGroups#DeleteNestedFieldGroupOnStructure

**Comment by alexcandidos** [comment]
Hey @Tim-Cao , we prefer to keep this test as is in Data Engine scope. Thanks !

**Comment by Tim-Cao** [comment]
Hi @alexcandidos, could you tell me what’s the difference between them? It doesn’t make sense to add two case with same steps

**Comment by Tim-Cao** [comment]
Got it. Thanks

**Comment by Tim-Cao** [comment]
See https://github.com/liferay-echo/liferay-portal/pull/3609
View total diff https://github.com/liferay-echo/liferay-portal/pull/3609/commits/a5e0f9c78baea359b0bdc288cab171960e24cf71

**Comment by Tim-Cao** [comment]
ci:close

**Pull request closed without merging**
