### PR TITLE
AC Test Fix - LRAC-9317 | master

### PR DESCRIPTION
**Pull request by andreefarias**
https://issues.liferay.com/browse/LRAC-9317 (test fix ticket)

### CODE REVIEW

**Comment by andreefarias** [comment]
ci:test:analytics-cloud:nocompile

**Comment by ViniLopes20** [comment]
ci:test:sf

**Comment by ViniLopes20** [comment]
ci:stop

**Comment by ViniLopes20** [comment]
ci:reopen

**Pull request closed without merging**
