### PR TITLE
AC Test Fix - LRAC-10927 | master

### PR DESCRIPTION
**Pull request by ViniLopes20**
https://issues.liferay.com/browse/LRAC-10927
[Testray](https://testray.liferay.com/home/-/testray/case_results?testrayCaseName=CanCreateNestedCriteria&testrayBuildId=1658044844&testrayRunId=1658129810)

### CODE REVIEW

**Comment by ViniLopes20** [comment]
ci:test:sf

**Review by joshitagaki — APPROVED** [review]
Nice fix LGTM!

**Review by manuferreira — APPROVED** [review]
LGTM! `viewGenericText` always a handy function haha :tada:

**Review by christianstokes — APPROVED** [review]
Looks good!

**Comment by christianstokes** [comment]
ci:forward

**Pull request closed without merging**
