### PR TITLE
LRAC-11006 | master

### PR DESCRIPTION
**Pull request by calvinctvo**
https://issues.liferay.com/browse/LRAC-11006
Adding 3 missing test case to isolation due to this [PR](https://github.com/liferay/com-liferay-osb-asah-private/pull/3557)

### CODE REVIEW

**Comment by calvinctvo** [comment]
ci:test:sf

**Comment by calvinctvo** [comment]
ci:test:sf

**Review by joshitagaki — APPROVED** [review]
LGTM

**Comment by calvinctvo** [comment]
ci:forward

**Review by ViniLopes20 — APPROVED** [review]

**Comment by ViniLopes20** [comment]
ci:forward

**Comment by ViniLopes20** [comment]
ci:forward

**Comment by ViniLopes20** [comment]
ci:stop

**Pull request closed without merging**
