### PR TITLE
AC Test fix - LRAC-10599 | master

### PR DESCRIPTION
**Pull request by joshitagaki**
Ticket: https://issues.liferay.com/browse/LRAC-10599
Another batch with fixed empty state messages

### CODE REVIEW

**Comment by joshitagaki** [comment]
ci:test:sf

**Review by ViniLopes20 — APPROVED** [review]
LGTM, thanks Josh

**Review by manuferreira — APPROVED** [review]
LGTM! Thanks Josh. :tada:

**Review by calvinctvo — APPROVED** [review]
LGTM @joshitagaki

**Review by christianstokes — APPROVED** [review]
Approved!

**Comment by christianstokes** [comment]
ci:forward

**Pull request closed without merging**
