### PR TITLE
AC Test fix - LRAC-10599 | master

### PR DESCRIPTION
**Pull request by calvinctvo**
https://issues.liferay.com/browse/LRAC-10599
Fixed empty state messages for second batch of tests

### CODE REVIEW

**Comment by ViniLopes20** [comment]
ci:test:sf

**Review by joshitagaki — APPROVED** [review]
LGTM!

**Review by manuferreira — APPROVED** [review]
LGTM! Thank you Calvin :crossed_swords:

**Comment by calvinctvo** [comment]
ci:forward

**Pull request closed without merging**
