### PR TITLE
AC Test Fix - LRAC-10995 | master

### PR DESCRIPTION
**Pull request by ViniLopes20**
https://issues.liferay.com/browse/LRAC-10995
[Testray](https://testray.liferay.com/home/-/testray/case_results/index?p_p_state=normal&orderByCol=status_sortable&orderByType=asc&testrayBuildId=1703345244)

### CODE REVIEW

**Review by manuferreira — APPROVED** [review]
LGTM, thanks Vini.

**Comment by christianstokes** [comment]
hey @ViniLopes20 I am curious about this.  Why does hard coding the name of the event help in this case?

**Comment by ViniLopes20** [comment]
Hey @christianstokes, I forgot to put this explanation in the PR description. In the other analysis tests the name of the custom event always ends with the name of the data source which in CI is different that's why we used `extractFirst`, but these tests were failing because they expected the name to have **liferay dxp**, I think that as these tests are isolated the behavior in the CI is different so I removed the `extractFirst`.

**Review by joshitagaki — APPROVED** [review]
LGTM! Yea I don't think there's an easy way to extract the data source to match.

**Review by christianstokes — APPROVED** [review]
Approved

**Comment by christianstokes** [comment]
ci:forward

**Pull request closed without merging**
