### PR TITLE
LPS-126376

### PR DESCRIPTION
**Pull request by alexcandidos**

### CODE REVIEW

**Comment by Tim-Cao** [comment]
Hi @alexcandidos, this case duplicates with LocalizedNestedFieldsStructure#TranslationDoesNotChangeAnother
See https://github.com/liferay-qa/liferay-portal/pull/174

**Comment by emanuelfisilva** [comment]
Hello @Tim-Cao , thanks for your review. We'll choose to keep these validations separate due to product's specificity strategy.

**Comment by Tim-Cao** [comment]
See https://github.com/liferay-echo/liferay-portal/pull/3768
View total diff https://github.com/liferay-echo/liferay-portal/pull/3768/commits/9a45ae7db5f8b98253608b3a8192ee97ef20f46d

**Comment by Tim-Cao** [comment]
ci:close

**Pull request closed without merging**
