### PR TITLE
AC Automated Test - LRAC-8832, LRAC-8128, LRAC-8785, LRAC-8787, LRAC-8788, LRAC-8790, LRAC-8792, LRAC-8793 and LRAC-8795| master

### PR DESCRIPTION
**Pull request by DebSouza**
https://issues.liferay.com/browse/LRAC-8832
https://issues.liferay.com/browse/LRAC-8128
https://issues.liferay.com/browse/LRAC-8785
https://issues.liferay.com/browse/LRAC-8787
https://issues.liferay.com/browse/LRAC-8788
https://issues.liferay.com/browse/LRAC-8790
https://issues.liferay.com/browse/LRAC-8792
https://issues.liferay.com/browse/LRAC-8795

### CODE REVIEW

**Comment by DebSouza** [comment]
ci:test:sf

**Comment by ViniLopes20** [comment]
ci:test:sf

**Comment by ViniLopes20** [comment]
ci:test:sf

**Comment by ViniLopes20** [comment]
Hi @DebSouza, I think there's a commit in this PR from another PR

**Comment by ViniLopes20** [comment]
ci:test:sf

**Comment by alexcandidos** [comment]
Hi @DebSouza , Thanks for working on it!

The code looks good to me!

I'm forwarding it.

**Comment by alexcandidos** [comment]
ci:forward

**Pull request closed without merging**
