### PR TITLE
LRAC-8948,LRAC-8991, LRAC-8992,LRAC-8993,LRAC-9003 | Master

### PR DESCRIPTION
**Pull request by Hanlf**
https://issues.liferay.com/browse/LRAC-8948
https://issues.liferay.com/browse/LRAC-8991
https://issues.liferay.com/browse/LRAC-8992
https://issues.liferay.com/browse/LRAC-8993
https://issues.liferay.com/browse/LRAC-9003

### CODE REVIEW

**Comment by Hanlf** [comment]
ci:test:sf

**Comment by alexcandidos** [comment]
starting to review...

**Comment by alexcandidos** [comment]
hi @Hanlf , could you please take a look at my suggestions? Thanks!

**Comment by Hanlf** [comment]
Hi @alexcandidos ,
Updated the tests, please review!

**Comment by alexcandidos** [comment]
hi @Hanlf , I just noticed @suilin also changed the `ACUtils#searchBar` macro here https://github.com/brianchandotcom/liferay-portal/pull/106532/commits/77c2cb73adcee42967a221eb776ddcc119934ead I think we'll have a logic conflict due to the way both of you changed that macro...

I think passing the `cardTitle` is better than using the index, however, the @suilin code is already on Brian's queue, feel free to close and resend if you decide it's better to keep the @Hanlf solution ... Could you please see how we could use the same solution to avoid this conflict? 

I'm sorry for the inconvenience.

**Comment by Hanlf** [comment]
Hi @alexcandidos 
Talked with @suilin, she will update her PR using `cardTitle` to search.  So you can safely forward my PR, thanks!

**Comment by suilin** [comment]
Hi @alexcandidos, I resend my PR on https://github.com/liferay-qa/liferay-portal/pull/893, thanks!

**Comment by alexcandidos** [comment]
Thanks @Hanlf  and @suilin for the teamwork! 🥇

**Comment by alexcandidos** [comment]
Hi @Hanlf , Thanks for working on it!

The code looks good to me!

I'm forwarding it.

**Comment by alexcandidos** [comment]
ci:forward

**Pull request closed without merging**
