### PR TITLE
LRAC-8346, LRAC-8347, LRAC-8348 | master

### PR DESCRIPTION
**Pull request by Tim-Cao**
https://issues.liferay.com/browse/LRAC-8346
https://issues.liferay.com/browse/LRAC-8347
https://issues.liferay.com/browse/LRAC-8348
https://issues.liferay.com/browse/LRAC-8345 is covered by https://issues.liferay.com/browse/LRAC-8347

This is only for master.

@alexcandidos

### CODE REVIEW

**Comment by Tim-Cao** [comment]
ci:test:sf

**Comment by Tim-Cao** [comment]
ci:test:sf

**Comment by Tim-Cao** [comment]
ci:test:sf

**Comment by Tim-Cao** [comment]
ci:test:sf

**Comment by alexcandidos** [comment]
Hi @Tim-Cao , Thanks for working on it!

The code looks good to me!

I'm forwarding it.

**Comment by alexcandidos** [comment]
ci:forward

**Pull request closed without merging**
