### PR TITLE
AC Automated Test - LRAC-10509,LRAC-10510,LRAC-10512,LRAC-10513 and LRAC-10514 | master

### PR DESCRIPTION
**Pull request by ViniLopes20**
https://issues.liferay.com/browse/LRAC-10509
https://issues.liferay.com/browse/LRAC-10510
https://issues.liferay.com/browse/LRAC-10512
https://issues.liferay.com/browse/LRAC-10513
https://issues.liferay.com/browse/LRAC-10514

### CODE REVIEW

**Comment by ViniLopes20** [comment]
ci:test:sf

**Comment by ViniLopes20** [comment]
Hey @alexcandidos, @AfonsoHSantos and @manuferreira, look at this [commit here](https://github.com/liferay-qa/liferay-portal/pull/1561/commits/014210747c5c11f101398a004bbc3905859a5b43). It was a new implementation of poshi, now we can use two lists at the same time in macros. We won't need to use `StringUtil.extractFirst` and `StringUtil.extractLast` for these cases.

**Comment by alexcandidos** [comment]
> Hey @alexcandidos, @AfonsoHSantos and @manuferreira, look at this [commit here](https://github.com/liferay-qa/liferay-portal/pull/1561/commits/014210747c5c11f101398a004bbc3905859a5b43). It was a new implementation of poshi, now we can use two lists at the same time in macros. We won't need to use `StringUtil.extractFirst` and `StringUtil.extractLast` for these cases.

This feature is a great addition to Poshi, I've been waiting for it for a while! The `extractFirst/Last` was not intuitive! Thanks for sharing it @ViniLopes20 ! FYI @r4ddek @joshitagaki @calvinctvo @christianstokes

**Comment by alexcandidos** [comment]
Hi @ViniLopes20 , Thanks for working on it!

The code looks good to me!

Please, just fix this conflict and update the PR. Feel free to forward it when it is done.

**Comment by ViniLopes20** [comment]
ci:forward

**Pull request closed without merging**
