### PR TITLE
AC Automated Test - LRAC-8507 | master

### PR DESCRIPTION
**Pull request by mateusralv**
Ticket: https://issues.liferay.com/browse/LRAC-8507

### CODE REVIEW

**Comment by mateusralv** [comment]
ci:test:sf

**Comment by mateusralv** [comment]
ci:test:sf

**Comment by alexcandidos** [comment]
Hi @mateusralv , Thanks for working on it!

The code looks good to me!

I'm forwarding it.

**Comment by alexcandidos** [comment]
ci:forward

**Pull request closed without merging**
