### PR TITLE
AC Automated Test - LRAC-9201 | master

### PR DESCRIPTION
**Pull request by rafaellajordao**
https://issues.liferay.com/browse/LRAC-9201

### CODE REVIEW

**Comment by rafaellajordao** [comment]
ci:test:sf

**Review by alexcandidos — COMMENTED** [review]
hi guys @christianstokes, @joshitagaki, @r4ddek, I think this case is similar to what I described here https://github.com/liferay-qa/liferay-portal/pull/957#pullrequestreview-750923810 . 

Also, since it is related to accounts, I don't know if we are able to automate right now... 

What do you think?

Thanks!

**Comment by joshitagaki** [comment]
@alexcandidos 
Agreed since it's related to accounts I don't think this can be automated at the moment

**Comment by alexcandidos** [comment]
Thanks for confirming @joshitagaki !

**Comment by alexcandidos** [comment]
Since it is related to accounts, I think we cannot automate it right now... I'm closing it and updating the test map as `Manual - Automation Blocked`.

**Pull request closed without merging**
