### PR TITLE
AC Automated Test - LRAC-8487 | master

### PR DESCRIPTION
**Pull request by 91nilo**
https://issues.liferay.com/browse/LRAC-8487
https://issues.liferay.com/browse/LRAC-8887 (Refactor)

### CODE REVIEW

**Comment by 91nilo** [comment]
ci:test:sf

**Comment by 91nilo** [comment]
Code from https://github.com/liferay-qa/liferay-portal/pull/883

**Comment by alexcandidos** [comment]
Hi @91nilo , Thanks for working on it!


I'm forwarding it.

**Comment by alexcandidos** [comment]
ci:forward

**Pull request closed without merging**
