### PR TITLE
AC Test Fix - LRAC-10732 | master

### PR DESCRIPTION
**Pull request by joshitagaki**
https://issues.liferay.com/browse/LRAC-10732

### CODE REVIEW

**Comment by joshitagaki** [comment]
ci:test:sf

**Comment by ViniLopes20** [comment]
Hey @joshitagaki, I think you were missing the change from _**list1**_ to _**sectionTitleList**_ in these other lines:

- Line 221
- Line 259
- Line 277

**Comment by joshitagaki** [comment]
Ahh you're right missed those other instances. Fixed @ViniLopes20

**Review by ViniLopes20 — APPROVED** [review]

**Comment by alexcandidos** [comment]
Hi @ViniLopes20 , Thanks for working on it!

The code looks good to me!

I'm forwarding it.

**Comment by alexcandidos** [comment]
ci:forward

**Pull request closed without merging**
