### PR TITLE
AC Automated Test - LRAC-8791, LRAC-8789 | master

### PR DESCRIPTION
**Pull request by LucasMonteiro10**
https://issues.liferay.com/browse/LRAC-8791

### CODE REVIEW

**Comment by ViniLopes20** [comment]
ci:test:sf

**Comment by joshitagaki** [comment]
Hi @LucasAcacio, this looks good to me!
cc: @alexcandidos

**Comment by alexcandidos** [comment]
Hi @LucasMonteiro10 , Thanks for working on it!

The code looks good to me!

I'm forwarding it.

**Comment by alexcandidos** [comment]
ci:forward

**Pull request closed without merging**
