### PR TITLE
AC Test Fix - LRAC-9305 | master

### PR DESCRIPTION
**Pull request by mateusralv**
https://github.com/mateusralv/liferay-portal/pull/1
https://issues.liferay.com/browse/LRAC-9305

### CODE REVIEW

**Comment by mateusralv** [comment]
ci:test:sf

**Comment by ViniLopes20** [comment]
Hi @mateusralv, I was in doubt if the **liferay dxp** page actually shows up in AC. I don't see the test accessing any page with this name, have you checked if it really appears?

```
for (var interests : list "liferay dxp,site,sports,science,technology") {
	ACInterests.viewInterests(interestName = "${interests}");
}
```

**Comment by mateusralv** [comment]
> Hi @mateusralv, I was in doubt if the **liferay dxp** page actually shows up in AC. I don't see the test accessing any page with this name, have you checked if it really appears?
> 
> ```
> for (var interests : list "liferay dxp,site,sports,science,technology") {
> 	ACInterests.viewInterests(interestName = "${interests}");
> }
> ```

Hi @ViniLopes20, yes, i checked this and the page is showing

**Comment by alexcandidos** [comment]
Hi @mateusralv , Thanks for working on it!

The code looks good to me!

I'm forwarding it.

**Comment by alexcandidos** [comment]
ci:forward

**Pull request closed without merging**
