### PR TITLE
AC Automated Test - LRAC-9082 | master

### PR DESCRIPTION
**Pull request by DebSouza**
https://issues.liferay.com/browse/LRAC-9082

### CODE REVIEW

**Comment by DebSouza** [comment]
ci:test:sf

**Comment by ViniLopes20** [comment]
ci:test:sf

**Comment by DebSouza** [comment]
ci:test:sf

**Comment by DebSouza** [comment]
ci:test:sf

**Comment by DebSouza** [comment]
ci:test:sf

**Comment by alexcandidos** [comment]
Hi @DebSouza , Thanks for working on it!

The code looks good to me!

I'm forwarding it.

**Comment by alexcandidos** [comment]
ci:forward

**Pull request closed without merging**
