### PR TITLE
LRAC-9683 | master

### PR DESCRIPTION
**Pull request by calvinctvo**
https://issues.liferay.com/browse/LRAC-9683
Original refactor ticket: https://issues.liferay.com/browse/LRAC-8721

### CODE REVIEW

**Comment by calvinctvo** [comment]
ci:test:sf

**Comment by calvinctvo** [comment]
ci:test:sf

**Comment by alexcandidos** [comment]
Hi @calvinctvo , Thanks for working on it!

The code looks good to me!

I'm forwarding it.

**Comment by alexcandidos** [comment]
ci:forward

**Pull request closed without merging**
