### PR TITLE
LPS 126382

### PR DESCRIPTION
**Pull request by alexcandidos**

### CODE REVIEW

**Comment by nikki-pru** [comment]
ci:test:sf

**Comment by nikki-pru** [comment]
ci:test:relevant

**Comment by Hanlf** [comment]
Reviewing...

**Comment by Hanlf** [comment]
Send it to @david-gutierrez-mesa for future review: https://github.com/david-gutierrez-mesa/liferay-portal/pull/64
Please see changes [here](https://github.com/austinchiang/liferay-portal/compare/ad6509c961af753e186c10d7692981bb353139ea~...bbeaaf7725f696f8bdc9b8ddb85fb15103cf1f95).

**Comment by david-gutierrez-mesa** [comment]
ci:close

**Pull request closed without merging**
