### PR TITLE
AC Automated Test - LRAC-8596 | master

### PR DESCRIPTION
**Pull request by lucassantanasantos**
https://issues.liferay.com/browse/LRAC-8590
https://issues.liferay.com/browse/LRAC-8596
https://issues.liferay.com/browse/LRAC-8591

### CODE REVIEW

**Comment by andreefarias** [comment]
ci:test:sf

**Comment by lucassantanasantos** [comment]
ci:test:sf

**Comment by lucassantanasantos** [comment]
ci:test:sf

**Comment by lucassantanasantos** [comment]
ci:test:sf

**Comment by alexcandidos** [comment]
Hi @lucassantanasantos , Thanks for working on it!

The code looks good to me!

I'm forwarding it.

**Comment by alexcandidos** [comment]
ci:forward

**Pull request closed without merging**
