### PR TITLE
LPS-126830

### PR DESCRIPTION
**Pull request by alexcandidos**

### CODE REVIEW

**Comment by austinchiang** [comment]
**Reviewing...** :hourglass_flowing_sand: :sunglasses: :headphones:

**Comment by austinchiang** [comment]
@gustavolimav  please try to break up tests, macros and paths into different commits next time. Thanks!
https://github.com/austinchiang/liferay-portal/pull/945

**Comment by austinchiang** [comment]
@alexcandidos @gustavolimav I realized that the test you should be working on writing is 

`DMFieldGroups#DeleteFieldGroupOnStructure` (LPS-126830, Scenario 23.17) not

`DMFieldGroups#DeleteNestedFieldGroupOnStructure` (LPS-126823, Scenario 23.13)

That test should have been sent by another person (it is [here](https://github.com/liferay-qa/liferay-portal/pull/160)). Can you resend with the proper test and LPS commit message? Thanks!

**Comment by alexcandidos** [comment]
Thanks for catching this @austinchiang !

**Pull request closed without merging**
