### PR TITLE
AC Test Fix - LRAC-10618 | master

### PR DESCRIPTION
**Pull request by joshitagaki**
https://issues.liferay.com/browse/LRAC-10618
Testray: https://testray.liferay.com/home/-/testray/case_results?testrayBuildId=1643458748

### CODE REVIEW

**Comment by joshitagaki** [comment]
ci:test:sf

**Comment by joshitagaki** [comment]
ci:test:sf

**Comment by ViniLopes20** [comment]
Hey @joshitagaki, very good man, this problem didn't happen locally because when he back to AC he always had to log in again, I think it doesn't happen in CI, he should go back to AC and still stay in `Test Test` account. This behavior is interesting. I think that's what happened, right?

**Comment by joshitagaki** [comment]
@ViniLopes20 yea during CI run the Test Test user isn't signed out after the initial setup so it needs a direct sign out if the login page isn't present. I didn't want to change the launchAC macro since this behavior only affects these two cases that require non-admin user. I might go back and add some changes to launchAC if we get more cases with non-admin users.

**Comment by ViniLopes20** [comment]
Very good @joshitagaki, I think we could not change the `launchAC` macro, we have other cases of non-admin users, but I believe that in these cases we already start the test by login in initially with the non-admin user, so the test is passing and correct in other cases.

**Review by ViniLopes20 — APPROVED** [review]

**Review by christianstokes — APPROVED** [review]
Looks good to me, thank you guys.

**Review by r4ddek — APPROVED** [review]
Looks good, thanks Josh! :D

**Review by manuferreira — APPROVED** [review]
Looks good, thanks Josh.

**Comment by ViniLopes20** [comment]
Hi team, Thanks for reviewing!

I'm forwarding it!

**Comment by ViniLopes20** [comment]
ci:forward

**Pull request closed without merging**
