### PR TITLE
AC Test Fix - LRAC-10910 | master

### PR DESCRIPTION
**Pull request by ViniLopes20**
https://issues.liferay.com/browse/LRAC-10910
[Testray](https://testray.liferay.com/home/-/testray/case_results/index?p_p_state=normal&orderByCol=status_sortable&orderByType=asc&testrayBuildId=1658039497)

### CODE REVIEW

**Comment by ViniLopes20** [comment]
ci:test:sf

**Review by joshitagaki — APPROVED** [review]
LGTM! Great job @ViniLopes20

**Review by manuferreira — APPROVED** [review]
LGTM, thank you Vini :tada:

**Review by christianstokes — APPROVED** [review]
Always love some code cleaning 😀

**Comment by christianstokes** [comment]
ci:forward

**Pull request closed without merging**
