### PR TITLE
LRAC-8918 | master

### PR DESCRIPTION
**Pull request by melodywu**
https://issues.liferay.com/browse/LRAC-8919
https://issues.liferay.com/browse/LRAC-8920

### CODE REVIEW

**Comment by melodywu** [comment]
ci:test:sf

**Comment by alexcandidos** [comment]
Hi @melodywu , Thanks for working on it!

The code looks good to me!

I'm forwarding it.

**Comment by alexcandidos** [comment]
ci:forward

**Comment by alexcandidos** [comment]
ci:forward

**Pull request closed without merging**
