### PR TITLE
LPS-126454

### PR DESCRIPTION
**Pull request by alexcandidos**

### CODE REVIEW

**Comment by Tim-Cao** [comment]
Hi @alexcandidos, this case is already covered by LocalizedSimpleFieldsStructure#CheckDefaultStructureTitleDisplayedOnStructureList

**Comment by alexcandidos** [comment]
Hey @Tim-Cao , I was reviewing this case with help of @emanuelfisilva  and we noticed the following:

The purpose of the test LocalizedSimpleFieldsStructure#CheckDefaultStructureTitleDisplayedOnStructureList is to check if the structure is listed using the default title locale (defaultStructureName), so it should finish at the line 60.

And the new test LocalizedSimpleFieldsStructure#DefaultTitlePersistsAfterTranslatingForAnotherLocale is to check if when opening the structure, the default structure title persists, like the assertion in the lines 119-122. The changes you made on the LocalizedSimpleFieldsStructure#CheckDefaultStructureTitleDisplayedOnStructureList at the line 62 is opening the structure in the translated locale followed by an assertion in the translated locale, what is different from what the test is LocalizedSimpleFieldsStructure#DefaultTitlePersistsAfterTranslatingForAnotherLocale was planned to validate.

What do you think?

Thank you!

**Comment by Tim-Cao** [comment]
Hi @alexcandidos, I understood. There is only one step is different. Do you prefer to add a new case or add more step in existing case?

**Comment by alexcandidos** [comment]
Hey @Tim-Cao  , we prefer to keep this test as is in Data Engine scope. Thanks !

**Comment by Tim-Cao** [comment]
Got it

**Comment by Tim-Cao** [comment]
See https://github.com/liferay-echo/liferay-portal/pull/3608
View total diff https://github.com/liferay-echo/liferay-portal/pull/3608/commits/45a6ea18e16ebb3eeb0ea728c72a9f50ebc67f6d

**Comment by Tim-Cao** [comment]
ci:close

**Pull request closed without merging**
