### PR TITLE
AC Test Fix - LRAC-9647 | master  

### PR DESCRIPTION
**Pull request by manuferreira**
https://issues.liferay.com/browse/LRAC-9647 (fix ticket)
https://issues.liferay.com/browse/LRAC-9645 (refactor ticket)
https://issues.liferay.com/browse/LRAC-9646 (bug ticket)

### CODE REVIEW

**Comment by manuferreira** [comment]
ci:test:sf

**Comment by joshitagaki** [comment]
ci:test:sf

**Comment by alexcandidos** [comment]
Hi @manuferreira , Thanks for working on it!

The code looks good to me!

I'm forwarding it.

**Comment by alexcandidos** [comment]
ci:forward

**Pull request closed without merging**
