### PR TITLE
LPS-126399

### PR DESCRIPTION
**Pull request by alexcandidos**

### CODE REVIEW

**Comment by Tim-Cao** [comment]
Hi @alexcandidos, this case is already covered by WebContentStructures#SelectImageFromDocumentsAndMediaInImageField and WebContentWithCustomStructures#AddWebContentWithImageField

**Comment by alexcandidos** [comment]
Hi @Tim-Cao , thanks for the review! Discussing with @emanuelfisilva , we'll keep them as is in the Data Engine scope.

**Comment by Tim-Cao** [comment]
See https://github.com/liferay-echo/liferay-portal/pull/3630
View total diff https://github.com/liferay-echo/liferay-portal/pull/3630/commits/2e97e58a73cf19b4ae55b7dd6e4045e6b8bdf976

**Comment by Tim-Cao** [comment]
ci:close

**Pull request closed without merging**
