### PR TITLE
AC Test Fix - LRAC-10657 | master

### PR DESCRIPTION
**Pull request by ViniLopes20**
https://issues.liferay.com/browse/LRAC-10657
[Testray](https://testray.liferay.com/home/-/testray/case_results/index?p_p_state=normal&orderByCol=status_sortable&orderByType=asc&testrayBuildId=1683396090)

### CODE REVIEW

**Comment by ViniLopes20** [comment]
ci:test:sf

**Review by joshitagaki — APPROVED** [review]
LGTM!

**Review by christianstokes — APPROVED** [review]
Looks good, thanks for documenting the pause clearly as well.

**Comment by christianstokes** [comment]
ci:forward

**Pull request closed without merging**
