### PR TITLE
LPS-182906 | master

### PR DESCRIPTION
**Pull request by liuxingye**
https://issues.liferay.com/browse/LPS-182906

cc @manoelcyreno @nikki-pru @Sharryxue

### CODE REVIEW

**Comment by liuxingye** [comment]
ci:test:sf

**Comment by liuxingye** [comment]
ci:test:sf

**Comment by Sharryxue** [comment]
Hello @liuxingye,
Thanks for adding the tests, shall we update the description and test summary to express the expectation of the tests directly.

**Comment by liuxingye** [comment]
Hi @Sharryxue thank you for reviewing the tests, I'll update them.

**Comment by Sharryxue** [comment]
Hello @gaborlovasdotcom,
Please review these tests when you available, thanks. Sorry I couldn't add you as the Reviewer until you accept the invitation.

**Comment by liuxingye** [comment]
The failed tests from security are not related to my changes.

**Comment by liuxingye** [comment]
ci:test:sf

**Comment by liuxingye** [comment]
Thanks @gaborlovasdotcom, I've rebased and resolved the conflicts, then added the TC numbers to the description.

cc @Sharryxue

**Review by gaborlovasdotcom — APPROVED** [review]
LGTM, can be forwarded.

**Comment by liuxingye** [comment]
ci:forward

**Pull request closed without merging**
