### PR TITLE
LRAC-9698 Reduce running time for certain long tests | master

### PR DESCRIPTION
**Pull request by joshitagaki**
https://issues.liferay.com/browse/LRAC-9698
https://testray.liferay.com/home/-/testray/runs?testrayBuildId=1577927116

### CODE REVIEW

**Comment by joshitagaki** [comment]
ci:test:sf

**Comment by joshitagaki** [comment]
These changes are to avoid long running tests timing out the build.

**Comment by alexcandidos** [comment]
Reviewing it @joshitagaki ! :)

**Comment by alexcandidos** [comment]
hi @manuferreira @ViniLopes20 @AfonsoHSantos @christianstokes @r4ddek   please take a look at this PR. 

@joshitagaki isolated some cases that were failing by timeout. We discovered that Poshi has a timeout per batch of tests (another thing Josh reduced from 7 to 5) ... so some of these tests have a loop with 50 max iterations in order to refresh the list and search for the element to workaround the processing time between an interaction on DXP and AC, which may cause a long execution time, causing the batch to be aborted impacting the others tests scheduled to run on the same batch too. 

We believe that by lowering the batch we could see some improvements, but also in some cases isolating the cases are also applicable.

For more information about this discussion with CI team, please take a look on this [LRCI-2602
Some Analytics Cloud tests are being aborted during runs](https://issues.liferay.com/browse/LRCI-2602?focusedCommentId=2557652&page=com.atlassian.jira.plugin.system.issuetabpanels%3Acomment-tabpanel#comment-2557652).


Thanks for working on it, @joshitagaki !

The code looks good to me!

I'm forwarding it.

**Comment by alexcandidos** [comment]
ci:forward

**Pull request closed without merging**
